### PR TITLE
Added requiresMainQueueSetup to prevent warning and future side-effects in RCCManagerModule

### LINKED ISSUE #1982: Module RCCManagerModule requires main queue setup (implement requiresMainQueueSetup)
### Issue Description

There is a warning from ReactNative 0.49.1:
``
Module RCCManagerModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
``

### Steps to Reproduce / Code Snippets / Screenshots

Is shown in Crome Debugger on start.

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

### PR DESCRIPTION
**Pull request by atkit**
closes #1982

### CODE REVIEW

**Comment by Titozzz** [comment]
Please merge this

**Comment by messense** [comment]
Can we merge this?

**Comment by valerybugakov** [comment]
Would be great to have this merged

**Comment by habovh** [comment]
This should really get merged

**Comment by rudolfs** [comment]
+1

**Comment by SudoPlz** [comment]
That PR has been sitting here for 4 months now.
Is there a reason that is not getting merged ?

@DanielZlotin ?

**Comment by SudoPlz** [comment]
Awesome, thanks!

**Comment by atkit** [comment]
@yogevbd thanks

**Pull request merged**
