### PR TITLE
Add support for React Native 0.60

### PR DESCRIPTION
**Pull request by robertying**
## Summary

This pull request makes RNN compatible with the latest RN 0.60.0-rc.2. Since there will not be fundamental changes in the same minor version, we can assure this pull request can work for some time.

## Changes

- Remove `MeasureSpecProvider` & `SizeMonitoringFrameLayout`. They no longer exist.
- Change imports to AndroidX, because RN 0.60 uses it as default.
- Add a new build flavor so users won't be effected even they stay on the old RN version.
- Update doc to demonstrate how to modify `MainApplication.java` to utilize RN new AutoLink feature.

## Tests

Since there is no API change, all tests apply to this pull request as long as it passes build.

### CODE REVIEW

**Comment by guyca** [comment]
Hey @robertying 
Thanks for the PR, I'll merge it and continue working on it in v3 branch. v2 won't support RN 0.60.

**Comment by enahum** [comment]
Any ETA for v3?

**Comment by guyca** [comment]
@enahum V3 is published, with RN 0.60 and AndroidX support. You're more than welcome to try it out and give feedback - `3.0.0-alpha.2`.
I'm mostly waiting for feedback from the community before making the official release.

**Comment by IanOnFire** [comment]
Hi @guyca,

Any chance v2 will support RN0.60?
We're using RNN for our production apps and we are not fond of upgrading to an alpha build to use 0.60.

**Pull request merged**
