### PR TITLE
Support RN 0.56

### PR DESCRIPTION
**Pull request by emiyake**
Fixes issue #3505  

The error only occurs in rnn-2.0.2397.

rnn-2.0.2395 works fine with rn-0.56.0.

### CODE REVIEW

**Comment by ujwal-setlur** [comment]
Can this be reviewed and merged please? This patch works on 2.0.2397 and the latest 2.0.2399

**Comment by birkir** [comment]
I'm using 2.0.2394 with 0.56.0 without any problems

**Comment by emiyake** [comment]
@birkir I think it works up to the rnn-2.0.2395 with rn-0.56.0.

**Comment by ujwal-setlur** [comment]
any updates on this? This (or an adapted version) is really needed for rn-0.56.0.

**Comment by dorthwein** [comment]
+1 currently blocking our release etc.... :( <3 y'all awesome project though :) 👍

**Comment by guyca** [comment]
Hey guys, support for RN 0.56 was just added in `2.0.2416`
Thanks a lot @emiyake for the PR 👍

**Pull request closed without merging**
