### PR TITLE
Created Podspec file For cocoapod install

### PR DESCRIPTION
**Pull request by Titozzz**

### CODE REVIEW

**Comment by anonrig** [comment]
Can we merge this? :/

**Comment by anonrig** [comment]
@guyca can you look at this?

**Comment by Titozzz** [comment]
Do you guys need any precisions on why i'm doing this ?

**Comment by DaBs** [comment]
@guyca Can this be merged? The lack of a podfile is currently creating issues where Header Search Paths has to be set for the project if React Native is installed via a pod as it can otherwise not find it, causing any CI build to fail for all eternity as a fresh npm install contains no Header Search Paths.

**Comment by Titozzz** [comment]
Hello, any update ?

**Comment by birkir** [comment]
@guyca 👍 

Hate to have to patch this all the time
https://github.com/ueno-llc/react-native-starter/tree/master/patches

**Comment by Riant** [comment]
@Titozzz
When I try to integrate React Native project with some other native project, pod install React-Native and its dependents is really a good solution.

so the podspec file is really need for someone.

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
