### PR TITLE
Add topBar button animations on iOS

### PR DESCRIPTION
**Pull request by yogevbd**
Adds the ability to use the system's default button animations.

```js
options: {
  topBar: {
    animateLeftButtons: true, // false by default for backward consistency
    animatedRightButtons: true // false by default for backward consistency
  }
}
```

### CODE REVIEW

**Comment by swabbass** [comment]
> Adds the ability to use the system's default button animations.
> 
> ```js
> options: {
>   topBar: {
>     animateLeftButtons: true, // false by default for backward consistency
>     animatedRightButtons: true // false by default for backward consistency
>   }
> }
> ```

Awesome, @yogevbd can we have a video screenshot?

**Comment by swabbass** [comment]
@yogevbd, This is an easy solution, wdyt? 


https://user-images.githubusercontent.com/7227793/119292016-34911780-bc58-11eb-8603-081c70c7c984.mov

**Comment by guyca** [comment]
@swabbass Amazing! This is exactly what I had in mind.

**Comment by yogevbd** [comment]
This is how it looks on iOS:

https://user-images.githubusercontent.com/10794586/119339675-2237cd80-bc9a-11eb-908e-558bd59e242b.mov

**Pull request merged**
