### PR TITLE
DOCS: Fixed android installation

### PR DESCRIPTION
**Pull request by brapifra**
The documentation for the android installation of v2 was wrong.

### CODE REVIEW

**Comment by guyca** [comment]
This is wrong, MainActivity should extend SplashActivity as the docs state.

**Comment by brapifra** [comment]
In v2 there is no SplashActivity, it was replaced by NavigationActivity. MainActivity tries to extend SplashActivity but fails because it doesn't exist.
https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java

**Comment by guyca** [comment]
Sorry, didn't notice this PR was for v2 branch 👍

**Comment by DanielZlotin** [comment]
We still need to add `createAdditionalReactPackages` or similar mechanism

**Pull request merged**
