### PR TITLE
Fix `kotlin` build issues with react native 73.x

### LINKED ISSUE #7819: Execution failed for task ':react-native-navigation:compileReactNative71DebugKotlin'.
### What happened?

Execution failed for task ':react-native-navigation:compileReactNative71DebugKotlin'.
> 'compileReactNative71DebugJavaWithJavac' task (current target is 17) and 'compileReactNative71DebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 1m 11s
619 actionable tasks: 619 executed

### What was the expected behaviour?

...

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

...

### In what environment did this happen?

React Native Navigation version: 7.37.2
React Native version: 0.73.0
Node version: v20.3.0
Device model: Pixel
Android version: 14
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by siddarthkay**
In this PR we do the following : 
- We make sure `react-native-navigation` uses java 17 which is needed by react-native 0.73.1
- We fix a type mismatch error when executing this `gradle` task `:react-native-navigation:compileReactNative71DebugKotlin`

fixes #7819

relevant patch in status-mobile repo : https://github.com/status-im/status-mobile/pull/18496/files#diff-b3d31b1df4cceb663a7dba96bcc3ea45686afe2208d7945b6e7e269067d753fbR100-R106

### CODE REVIEW

**Comment by Spxc** [comment]
Any status on release for this?

**Comment by siddarthkay** [comment]
Tests are failing, I'll try to fix the tests this weekend

**Comment by Spxc** [comment]
> Tests are failing, I'll try to fix the tests this weekend

Thanks, i did a PR as well (with test failing, what a surprise haha), with a bit more changes to the `ButtonPresenter`

https://github.com/wix/react-native-navigation/pull/7842

**Review by ovidiubularda — APPROVED** [review]
LGTM - 😃

**Comment by siddarthkay** [comment]
Hi @asafkorem @d4vidi @yogevbd 
How important is `postCommandsOnMainThread_doesNotCrashIfActivityIsNull` test? can this be skipped?
This is the only test that fails on this PR when i run `npm run test-unit-android -- --release`

If not could you please provide some assistance here so that we can make progress on this PR :)

Thank you

**Comment by siddarthkay** [comment]
closing in favour of https://github.com/wix/react-native-navigation/pull/7864

**Pull request closed without merging**
