### PR TITLE
Android: Fix an issue with incorrect Lightbox measurments.

### PR DESCRIPTION
**Pull request by jbettcher**
Due to a race condition, the height and width of the Lightbox screen
may be read too early, resulting in a zero-width or height lightbox.

Addresses Content of lightbox not displayed #2288

### CODE REVIEW

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by jkappers** [comment]
Adding a comment so this doesn't close. I worked and merged this PR for my own use and it fixes the issue. Would love to see it merged and verified if possible. ♥️

**Comment by ycswaves** [comment]
any updates on this?

**Comment by ycswaves** [comment]
Thank you!

**Pull request merged**
