### PR TITLE
Restore bottomTabs visibility when needed

### LINKED ISSUE #6282: not hidding bottomTabs after navigate to child
### Issue Description

1. Set default options
bottomTabs: {
      animate: true,
      drawBehind: false,
      visible: false,
    },

2. Create root bottom tabs screen
bottomTabs: {
          visible: true,
          animate: true,
          drawBehind: true,
          currentTabIndex: 0,
          titleDisplayMode: 'alwaysShow',
        },

3. Navigate to child screen (with settings)
bottomTabs: {
          visible: false,
          animate: true,
          drawBehind: true,
        },

Result: bottom tabs not hidding (working on 6.4 and 6.5)

---
### Environment
* React Native Navigation version: 0.62.2
* React Native version: 6.7.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): debug

### PR DESCRIPTION
**Pull request by yogevbd**
Until now, `tabBar.frame` got restored each time child appeared which resulted in wrong bottomTabs visibility.
In this PR we changed it so the `tabBar.frame` will get restored only after the tabBar frame has changed through `mergeOptions`.

Closes #6282

### CODE REVIEW

**Comment by guyca** [comment]
@nazrdogan You've described a code behaviour, what is the bug you're actually seeing?

**Comment by nazrdogan** [comment]
@guyca bottomTabs visible doesn't not effect.  I set false but it's visible.

**Comment by guyca** [comment]
@nazrdogan gotcha. Have you tried with version 6.7.5?

**Comment by nazrdogan** [comment]
@guyca  yeah. i've tried same behaviour.

**Comment by guyca** [comment]
Can you please open an issue with a reproduction scenation? Would help if you can reproduce in the Playground app. Thanks! 👍

**Comment by nazrdogan** [comment]
```
    function setRoot() {
       Navigation.setRoot({
        root: {
            bottomTabs: {
                options: {
                    bottomTabs: {
                        visible: false,
                        drawBehind: true,
                        animate: false,
                    },
                },
                children: [
                    {
                        component: {
                            name: 'Layouts',
                            options: {
                                topBar: {
                                    visible: false,
                                    height: 0,
                                },
                                bottomTab: {

                                },
                                sideMenu: {
                                    right: {
                                        enabled: false,
                                    },
                                },
                            },
                        },
                    },
                    {
                        component: {
                            name: 'Options',
                            options: {
                                topBar: {
                                    visible: false,
                                    height: 0,
                                },

                                sideMenu: {
                                    right: {
                                        enabled: false,
                                    },
                                },
                            },
                        },
                    },
                ]
            }
        }
    });
     }

```
I changed setRoot of Playground app like this. if I use bottom tabs without stack child. problem occurs. Android just work fine.

Screenshot 2020-06-20 at 00 49 02
@guyca

**Comment by yogevbd** [comment]
@nazrdogan fixed in #6324 🙏

**Comment by nazrdogan** [comment]
Thank you @yogevbd  @guyca

**Pull request merged**
