### PR TITLE
A few improvements for Android

### PR DESCRIPTION
**Pull request by viotti**
### 1

Sidemenus weren't clickable on Android. It seems the order in which child views were being added to parent controllers, left or right before center, was affecting the ability to interact with the menus.  I've changed the code to always add them in a specific order: center, then left, then right.

I believe this closes issue #2835.

### 2

On Android, merging options to open a menu works.

```
  Navigation.mergeOptions(currentComponentId, {
      sideMenu: {
          left: {
              visible: true
          }
      }
  })
```

But merging options to close it wasn't working.

```
  Navigation.mergeOptions(currentComponentId, {
      sideMenu: {
          left: {
              visible: false
          }
      }
  })
```

### 3

The bottom tabs controller was reserving a margin space for the bottom tabs when switching from one to another, regardless of its visibility settings.

### CODE REVIEW

**Comment by guyca** [comment]
Hey @viotti 
Sorry for the late response. Can you please resolve the conflicts so we can move forward with the PR?

**Comment by viotti** [comment]
Absolutely @guyca. Can you give me until tomorrow? I'm on another project right now but will come back to React Native tomorrow.

**Comment by viotti** [comment]
Thanks for having a look at this BTW.

**Comment by guyca** [comment]
Sure thing @viotti, take your time 👍

**Comment by viotti** [comment]
@guyca done. I took the liberty of doing a rebase + forced push into my fork, instead of doing a merge, to resolve the conflicts.

**Pull request merged**
