### PR TITLE
[v2][Android] bottomTab selected icon support

### PR DESCRIPTION
**Pull request by hadimostafapour**
Support bottomTab selected Icon on Android

```javascript
{
    bottomTab: {
       icon: require('./inactive-icon.png'),
       selectedIcon: require('active-icon.png'), // Same as iOS implementation
       text: 'Tab Test'
   }
}
```

### CODE REVIEW

**Comment by dao-wkm** [comment]
I got a crash here
image

Add this line below to fix it
`if (icon == null) icon = (ImageView) view.findViewById(R.id.bottom_navigation_small_item_icon);`

**Comment by CristianOspina** [comment]
Any progress on this? :(

**Comment by henrikra** [comment]
@hadimostafapour Are you going to fix those merge conflicts?

**Comment by TiagoCoelhoB** [comment]
Hi, any progress on this?

**Comment by hadimostafapour** [comment]
@henrikra @TiagoCoelhoB, I will fix the conflicts and minor bugs in the next few days, hope to get merged into the main repository finally.

**Comment by TiagoCoelhoB** [comment]
> @henrikra @TiagoCoelhoB, I will fix the conflicts and minor bugs in the next few days, hope to get merged into the main repository finally.

Thanks

**Comment by hadimostafapour** [comment]
I've created a new pull request for this, check out #4574

**Pull request closed without merging**
