### PR TITLE
[v2][Android] Add sideMenu height and width options for consistency with IOS

### PR DESCRIPTION
**Pull request by dpnolte**
Dear Maintainers,

Thanks for the awesome library.
Hereby my pull request for adding height and width options for Android. The width option already worked for IOS and this PR makes it consistent.
The options can be set in sideMenu for left and/or right, i.e.: `options { sideMenu: { left: { width: 200 } }.`

It is a minor change in SideMenuOptions and SideMenuController. Nevertheless, I've added unit tests to SideMenuControllerTest. I also ran yarn test-all without any issues.

Please let me know if any changes are necessary.

Cheers, Derk

### CODE REVIEW

**Comment by Lube** [comment]
@dpnolte this is not working for me do, you have some examples to follow?

```
  componentDidMount() {
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          visible: true,
          enabled: true,
          width: 50,
        },
      },
    })
  }
```

RNN react-native-navigation-2.0.2452
RN 0.56.0

**Comment by dpnolte** [comment]
Hi Sebestian,

Hmmm didn't thought about the merge options case. When you call mergeOptions, you change the view dimensions after the views are created. Do you do that on purpose? Maybe I can add mergeOptions support in a PR.
if you add the following to your component, it should work though:
`static get options() {
  {
      sideMenu: {
        left: {
          visible: true,
          enabled: true,
          width: 50,
        },
      },
  }
}`

**Comment by Lube** [comment]
I still can't get it to work even if specified as static options :<

**Comment by dpnolte** [comment]
And if you try the following:
```
 Navigation.setRoot({
    root: {
      sideMenu: {
        options: {
          sideMenu: {
            left: {
              width: 260,
            },
          },
        },
        left: {
          component: {
            id: COMPONENTS.SCREENS.SIDEBAR,
            name: COMPONENTS.SCREENS.SIDEBAR,
          },
        },
        center: {
          stack: {
            children: [
              {
                component: {
                  id: COMPONENTS.CONTAINERS.HOME,
                  name: COMPONENTS.CONTAINERS.HOME,
                },
              },
            ],
          },
        },
      },
    },
  });
```

**Comment by Lube** [comment]
That actually works, you are a beast! I'll make a PR updating the docs, can you figure out why is not working with static options and mergeOptions?

**Pull request merged**
