### PR TITLE
Destroy navigation activity layouts on catalyst instance destroy

### PR DESCRIPTION
**Pull request by ericketts**
The changes in this PR are to address #2331 & Microsoft/react-native-code-push#1144.

I've tried it on a few devices and it seems to consistently prevent the crash from occurring; that said, I'm a bit wary that the `runOnUiThread` is introducing a race condition that may fail to prevent the bug under the right circumstances. Any thoughts on tackling this (potential) issue?

Edit: I should also mention I'm aware that V1 PRs are not being accepted at this time, but wanted to submit this at least for others that are struggling with this bug to implement the solution on their forks.

### CODE REVIEW

**Comment by ericketts** [comment]
awesome to see this merged guys, thanks a bunch for taking the time to review!

unfortunately V2 seems to suffer from the same issue but this solution will not work for it (afaik V2 doesn't keep a statically accessible ref to the activity); given our use case I'll need to fix that eventually as well and will PR it too whenever I get time to work on it.

**Comment by levynir** [comment]
Thanks @guyca & @ericketts , drinks on me when any of you come to Hertzelia, Israel anytime soon .

**Comment by guyca** [comment]
@ericketts Thank you. If you could write a failing detox test for v2, we'll fix this asap. @levynir drinks on me if you manage to come to our [meetup](https://www.meetup.com/React-Native-TLV/events/255511586/) 👍

**Comment by ericketts** [comment]
@levynir no plans on the horizon but certainly somewhere I've wanted to visit for a while now, thanks much for the offer its very generous. 

@guyca to your point about a failing detox test, I'm not sure what the best way to do this would be, since as far as I can tell we'd need to either add the restart lib or a command to RNN that does what the restart lib does (ie calling `ReactInstaceManager#recreateReactContextInBackground()`) to properly recreate the crash scenario. do either of these seem like viable options, or any ideas for other options I may have missed?

as far as a fix though, I've adapted this fix to V2 and so far in my testing I have been crash free so I may have something for that soon.

**Pull request merged**
