### PR TITLE
V2 Android update pop animation does not work

### PR DESCRIPTION
**Pull request by qiepeipei**
update pop animation does not work

### CODE REVIEW

**Comment by qiepeipei** [comment]
@guyca mergeOptions and setDefaultOptions not work.

follow is my default options , push animation is ok, but pop is not work .

```
Navigation.setDefaultOptions({
    animations: {
        push: {
            content: {
                x: {
                    from: 200,
                    to: 0,
                    duration: 260,
                    interpolation: 'accelerate',
                }
            }
        },
        pop: {
            content: {
                x: {
                    from: 0,
                    to: 1000,
                    duration: 300,
                    interpolation: 'decelerate',
                }
            }
        }
    }
});
```

**Comment by qiepeipei** [comment]
@guyca https://github.com/wix/react-native-navigation/issues/3869#issuecomment-421143106

**Comment by guyca** [comment]
Hey @qiepeipei , This should be fixed in version 2.0.2592

**Comment by banli17** [comment]
@guyca   no , "react-native-navigation": "^2.0.2597",   is the same, pop is not work. also is from top to bottom.

```
       pop: {
            content: {
                x: {
                    from: 0,
                    to: 800,
                    duration: 270,
                    interpolation: 'accelerate'
                },
                alpha: {
                    from: 1,
                    to: 0,
                    duration: 220,
                    interpolation: 'accelerate'
                }
            }
        }
```

**Comment by guyca** [comment]
Where are you declaring the pop animation?

**Comment by banli17** [comment]
@guyca   Navigation.setDefaultOptions

**Comment by guyca** [comment]
This will be resolved in 2.0.2603. Thanks for reporting @qiepeipei and @banli17

**Pull request closed without merging**
