### PR TITLE
Add CocoaPods support to v1

### PR DESCRIPTION
**Pull request by ceyhuno**

### CODE REVIEW

**Comment by ceyhuno** [comment]
@eliperkins There is already a [podspec](https://github.com/wix/react-native-navigation/blob/v2/ReactNativeNavigation.podspec) in the v2 branch. The owner of that can own this too. This one is just for others who cannot use v1 yet and who wants to have Cocoapods support

**Comment by alfonsodev** [comment]
Can you please merge this @eliperkins ?
We are keeping a fork of the project just because this file is missing.
This file will only affect people using Pod.
Thanks

**Comment by eliperkins** [comment]
@alfonsodev I am not a maintainer of this library, so I can't merge this, nor can I push it to CocoaPods trunk. I am just a contributor to this library.

**Comment by ceyhuno** [comment]
Maybe @DanielZlotin @guyca @gran33 can help?

**Comment by birkir** [comment]
@guyca should be able to help with this one. Small effort for huge gain.
@ceyhuno can you merge with upstream.

I always keep a patch in my project that gets applied on postinstall (adds the podspec), before pod install.

**Comment by chaitanya0bhagvan** [comment]
@alfonsodev I copy [ReactNativeNavigation.podspec](https://gist.github.com/chaitanya0bhagvan/bcafe5fd493e6f4b7371d059f9e6cdde) to the root of my project and add the following line to Podfile

`pod 'ReactNativeNavigation', :path => '../ReactNativeNavigation.podspec'`

I do this for any library that does not support Cocoapods

**Comment by anonrig** [comment]
@chaitanya0bhagvan After doing what you already did, I receive "RCCManager.h" couldn't found error. It seems that the build phase script isn't added to the project. How do you add it through CocoaPods?

**Comment by chaitanya0bhagvan** [comment]
@anonrig If you could create a sample repo it would be helpful to debug the issue.

**Pull request closed without merging**
