### PR TITLE
[v2] fixed #3521

### LINKED ISSUE #3521: [V2] Topbar title style is not working when state is disabled or highlighted on iOS
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

On iOS, the style for the title of Topbar right buttons is different when button state is highlighted and disabled.
I expect the font settings match with normal.

#### Screenshots

- normal

normal

- highlighed

highlighted-before

- disabled

disabled-before

#### Config

```
topBar: {
      noBorder: true,
      rightButtons: [
        {
          id: "setting",
          title: "Settings",
          fontFamily: "Futura",
          color: "#666666",
          fontSize: 20,
          // enabled: false
        }
      ]
    }
```

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

### PR DESCRIPTION
**Pull request by masarusanjp**
Fixed #3521 

## What to do

I fixed it to use the same font as normal even disabled and highlighted

### normal

normal

### highlighed

before | after
--- | ---
highlighted-before | highlighted-after

### disabled

before | after
--- | ---
disabled-before | disabled-after

### CODE REVIEW

**Comment by masarusanjp** [comment]
> 11:28:33 tslint lib/src/**/*.[tj]s* integration/**/*.[tj]s* e2e/**/*.[tj]s scripts/**/*.[tj]s* playground/src/**/*.[tj]s* --format verbose
11:28:35 ERROR: (no-console) lib/src/components/ComponentWrapper.test.tsx[52, 18]: Calls to 'console.error' are not allowed.
11:28:35 ERROR: (no-console) lib/src/components/ComponentWrapper.test.tsx[53, 5]: Calls to 'console.error' are not allowed.
11:28:35 ERROR: (no-console) lib/src/components/ComponentWrapper.test.tsx[57, 5]: Calls to 'console.error' are not allowed.

Why did CI fail?
It seems `tslint.config` contains ` "no-console": [false],` .

**Comment by chrise86** [comment]
Any news on this @masarusanjp ?

**Comment by masarusanjp** [comment]
test this please

**Comment by masarusanjp** [comment]
@chrise86 

No news 😢 
I'm waiting for review by @wix 's stuff.

**Comment by masarusanjp** [comment]
@yogevd Thanks for reviewing !

**Pull request merged**
