### PR TITLE
[v2] [iOS] Ignore pan gesture when no drawer is enabled

### PR DESCRIPTION
**Pull request by StasDoskalenko**
Fix for https://github.com/wix/react-native-navigation/issues/3462
PanResponder callbacks do not work correctly if an RNN drawer was inited, but later disabled.

In the instance of a left drawer, for example, this pull request will allow the following code to prevent RNN from "stealing" a gesture:

```js
onPanResponderGrant: (e, gestureState) => {
    Navigation.mergeOptions(componentID, {
      sideMenu: {
        left: {
          enabled: false,
        },
        right: {
          enabled: false,
        },
      },
    })
},
```

```js
onPanResponderRelease: (e, gestureState) => {
    Navigation.mergeOptions(componentID, {
      sideMenu: {
        left: {
          enabled: true,
        },
        right: {
          enabled: false,
        },
      },
    })
    ...
}
```

Based on the PR https://github.com/wix/react-native-navigation/pull/2578

### CODE REVIEW

**Comment by Flavien** [comment]
Would be great to have this merged.

**Comment by Flavien** [comment]
This doesn't seem to work in `2.12`. I have a left menu but it isn't enabled, and the horizontal swipe gesture is still not working. Here is my setup:

```
    Navigation.setRoot({
        root: {
            sideMenu: {
                left: {
                    component: {
                        name: "MyApp.Sidebar",
                        id: AppNavigation.sideBarComponentId,
                        options: {
                            statusBar: NavigatorStyles.default.statusBar
                        }
                    }
                },
                center: {
                    stack: {
                        children: [AppNavigation.getComponent(initialScreen)],
                        options: {
                            topBar: {
                                title: {
                                    text: "My App"
                                }
                            },
                            sideMenu: {
                                animationType: "parallax",
                                left: {
                                    enabled: false
                                }
                            }
                        }
                    }
                }
            }
        }
    });
```

**Comment by guyca** [comment]
@Flavien Can you try rendering the swipeable component after component appeared? Something like this:

```js
componentDidAppear() {
    this.setState({showSwipeableComponent: true});
  }
render(){
   return this.state.showSwipeableComponent && <SwipeableComponent />
}
```

We suspect there's an issue in 2.12.0 related to ViewController measurements, we'll look into it today.

**Comment by Flavien** [comment]
Actually, I managed to make it work by disabling also the right side (even though it doesn't have a right sidebar).

**Comment by Hesowcharov** [comment]
@Flavien your advice works for me. Thanks!

**Comment by barclayd** [comment]
Thanks very much for this great pull request. I believe an issue is still present within the code base that limits the PanResponder when sideMenu is used at some point within the application. I opened an issue for this myself and subsequently found a fix for the issue here: https://github.com/wix/react-native-navigation/issues/4826

For others still facing issues with PanResponder gestures being limited, I believe this fix should help - setting ``openGestureMode: 'bezel',`` as used in a function that defines navigation default options such as the one below:
```
 Navigation.setDefaultOptions({
        topBar: {
            visible: false
        },
        statusBar: {
            style: "light"
        },
        sideMenu: {
            openGestureMode: 'bezel',
            left: {
                visible: true,
                enabled: true
            },
            right: {
                visible: false,
                enabled: false
            }
        }
    });
};
```

**Comment by StasDoskalenko** [comment]
@barclayd you could also try to disable both menus for onPanMove function, after - enable them again

**Comment by jdegger** [comment]
This issue has been gone for a long time but it's back now. We recently updated from 6.4.0 to 6.9.1 and now it's back.

I'm looking at the commits but can't seem to find this issue. Anyone any clue?

**Comment by guyca** [comment]
@jdegger Can you please push a reproduction and open a new issue with more information?

**Pull request merged**
