### PR TITLE
Creating Fab&Snackbar layout only when needed

### PR DESCRIPTION
**Pull request by ifsnow**
Related to #2160

I want to create fab&snackbar layout only when I need it.
I think It can solve the issue with `react-native-youtube`, and It's also a gain in performance in some cases.

Please review it positively.

### CODE REVIEW

**Comment by guyca** [comment]
Hey @ifsnow 
Could you please upload a project where this issue is reproducible? I'd like to take a stab at it.

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by ziyafenn** [comment]
Hey guys. This issue is still exists! @guyca do you think you could take a look into this issue? Otherwise it's impossible to use youtube library with your navigation.

**Comment by mojomoth** [comment]
This issu is still exists on RNN v1
Thank you @ifsnow

**Pull request closed without merging**
