### PR TITLE
[v2][iOS][Feature] - Customizable badge size

### PR DESCRIPTION
**Pull request by maleriepace**
Added a parameter to allow for a custom badge size in iOS. 
Custom badge sizes were already allowed in Android by adding [dimens.xml](https://github.com/aurelhubert/ahbottomnavigation/blob/c4114c23213f0e86216f75b2770964dbc02eebb0/demo/src/main/res/values/dimens.xml) to your project.

### CODE REVIEW

**Comment by maleriepace** [comment]
This code also fixes a bug introduced in v2.0.2583 2afbfd6e678ba7079daae30644ab7cf97891ab0c which caused tab items to display without associated badges until they were selected.

**Comment by pribeh** [comment]
@maleriepace Thanks for attempting this. Can the badge position be adjusted?

**Comment by maleriepace** [comment]
@pribeh It can not be adjusted as of this PR. The badge will appear in the top right corner.

**Comment by maleriepace** [comment]
__Example of the badgeSize set to 10__
image

__Example of the badgeSize set to 30__
image

**Comment by maleriepace** [comment]
Any chance you will merge this in?

**Comment by guyca** [comment]
Hey @maleriepace 
Sorry for the delay and thanks for the PR. We'll get to this in the next week or two. We're trying to wrap up a few iOS bugs and finally merge v2 to master, so we'd like to wait with new iOS features.

**Comment by LRNZ09** [comment]
This would be really useful

**Comment by matpaul** [comment]
@guyca Any updates on this PR ?

**Comment by hnsa** [comment]
Will this PR be part of a future release? This would be useful!

**Comment by maleriepace** [comment]
Is this going to be merged any time soon? I don't have a ton of time on my hands to continue maintaining it and this PR has been open for 7 months now.

**Comment by guyca** [comment]
I've tried out this approach - the calculations done here in order to figure out where to position the badge are wrong for tablets. I'm closing the PR and work on implementing this soon.

**Pull request closed without merging**
