### PR TITLE
Fixed issue with pop gesture causing a pushed screen not to display

### PR DESCRIPTION
**Pull request by ujwal-setlur**
Fixes issue #3576 

Reference: https://stackoverflow.com/questions/46119761/uinavigation-pushviewcontroller-doesnt-display-next-view-but-runs-the-code

### CODE REVIEW

**Comment by ujwal-setlur** [comment]
Developers @guyca @yogevbd this PR has been open a long time. No comments on it. Any issues?

**Comment by matpaul** [comment]
Hi @guyca, can you merge it?

Reproduceble in hecla

**Comment by matpaul** [comment]
@ujwal-setlur oh, i pull this fix and all pop gestures are not working =(

**Comment by ujwal-setlur** [comment]
Was working for me when I checked. Did you revert the change and make sure it started working again?

**Comment by matpaul** [comment]
@ujwal-setlur yep, 

so if interactivePopGestureRecognizer.enabled = NO ---> pop gestures not work at all (i try using  popGesture: false/true - no success)

remove it and everything is work - but with this crappy bug =( 

My screen was simple in stack (no tabbars)

**Comment by ujwal-setlur** [comment]
@matpaul, that's a bummer 😒. Unfortunately, I can't look into this much since I don't use react-native-navigation anymore.

**Comment by ujwal-setlur** [comment]
@matpaul, can you try setting enabled to YES? Not sure if that will help

**Comment by matpaul** [comment]
@ujwal-setlur i try, does't help, thanks for your response

**Comment by matpaul** [comment]
@guyca Can you help? this is very high priority bug (application freeze =( ) Thank you!

**Comment by ujwal-setlur** [comment]
You may want to reopen the bug. Got marked as stale

**Comment by matpaul** [comment]
@ujwal-setlur it's open (bot clear stale)

**Pull request closed without merging**
