### PR TITLE
Now allowing the custom nav bar to take up the whole space on iOS

### PR DESCRIPTION
**Pull request by SudoPlz**
The custom nav bar on iOS was really just a custom view applied to the title of the navigation bar.
There were problems with this approach, because the navigation bar messes up the frame of the title very frequently, especially when the orientation is changing. That behaviour is accepted when the title is a label, but not when we have a custom component.

With this pull request the custom nav bar component can take up the full width of the navigation bar, no matter what orientation we're at.

- That should also fix: https://github.com/wix/react-native-navigation/issues/1893

Here's how the issue looks like in RL:
<a href="https://cl.ly/2A3F0g3Y0k3u" target="_blank"></a>

and here's how it looks after the Pull Request:
<a href="https://cl.ly/3R281U001Z15" target="_blank"></a>

Notice how the pink component (Custom Nav Bar component defined in JSX) now takes up the full width of the nav bar.

### CODE REVIEW

**Comment by DiederikvandenB** [comment]
Why was this PR reverted? See 1399c7b48680150eb29ff3aa4deae96ad47057fc. I am facing the reported issue too.

**Comment by SudoPlz** [comment]
Yeah, we really need that fix in our project too. We had to use our own repo because of that revert.

**Comment by guyca** [comment]
@DiederikvandenB @SudoPlz This pr caused buttons to be unresponsive, the custom view was positioned over the buttons preventing them from handling touch events.

**Comment by SudoPlz** [comment]
@guyca in willing to fix that, can you please share an example repo where that issue happens? I'd be grateful.
Thank you!

**Comment by guyca** [comment]
@SudoPlz From what I remember, it was a screen with a custom nav bar component and right/left buttons.

**Comment by SudoPlz** [comment]
God it thanks @guyca I'll try to reproduce that, edit the commit and resubmit.

**Comment by SudoPlz** [comment]
@guyca I reopened this one. It seems like a false flag, check https://github.com/wix/react-native-navigation/pull/2620 out.

**Comment by Nickersoft** [comment]
Any update on getting #2620 merged/reviewed? I had been facing this same issue when I used this library multiple months ago and have been watching this issue closely since then. I've been sticking to [react-navigation](https://github.com/react-navigation/react-navigation) until it gets merged, as my app uses a custom gradient navbar.

**Comment by SudoPlz** [comment]
I'm waiting for someone to review for a month now. They're busy working on v2.

**Comment by Nickersoft** [comment]
@SudoPlz Damn that's aggravating... but understandable I suppose. I'd say @guyca but he's been tagged multiple times with no response, so he's pretty busy I imagine. I'm just surprised this was ever an issue to begin with. I guess for now I'll just your fork directly until some progress is made here, as well as report back with any issues if I come across them.

**Comment by SudoPlz** [comment]
I think @guyca deals with Android issues, and that's an iOS issue. Yeah, I'm using my own fork as well until they bake that back in.

**Comment by SudoPlz** [comment]
@Nickersoft looks like https://github.com/wix/react-native-navigation/pull/2620 was merged.

**Comment by Nickersoft** [comment]
@SudoPlz Yep! Just saw that. Exciting stuff 😃

**Pull request merged**
