### PR TITLE
Fix PlatformColor parsing on Android when using dark and light theme

### PR DESCRIPTION
**Pull request by svbutko**
Fixes: #7255

### CODE REVIEW

**Comment by svbutko** [comment]
I checked #6618 and it partially exists until this time, like I can't use a primary color like `?attr/colorPrimary` if I use material theme (e.g. `Theme.MaterialComponents.DayNight`) but it might have something to do with this:

https://github.com/facebook/react-native/issues/29763

**Comment by svbutko** [comment]
Maybe it would be better to completely change this behaviour and always put `JSONParser.convert(color)` because under the hood the value expects to be of `ReadableMap` type?

**Comment by yogevbd** [comment]
@swabbass wdyt?

**Review by swabbass — APPROVED** [review]

**Comment by swabbass** [comment]
you should not assign  `PlatformColor`  value to dark/light, it should replace the whole object since PlatformColor is a native way to achieve dark/light, hence, you define the same value in for example style.xml and style.night.xml and then assign the value to it, not assigning same value for both light and dark which is that what was being done natively

**Pull request closed without merging**
