### PR TITLE
Fix Android project warnings

### PR DESCRIPTION
**Pull request by svbutko**
Also fixes: #7264

### CODE REVIEW

**Comment by swabbass** [comment]
That is Great!.. Thanx dude.
How come we did not face such stuff in our #7034?

**Review by swabbass — APPROVED** [review]
You are awesome!

**Comment by svbutko** [comment]
I just noticed an issue that there are some logs from LogCat and then checked warnings in Android Studio and I was shocked a bit 😄

**Comment by svbutko** [comment]
About to do the same with iOS, I've seen several warnings in Xcode before

**Comment by swabbass** [comment]
> I just noticed an issue that there are some logs from LogCat and then checked warnings in Android Studio and I was shocked a bit 😄

Yup since we are 2, one android dev and one iOS, we did not have time to deal with such stuff since there is more prioritized stuff, we are blessed that you are here dude!

**Pull request merged**
