### PR TITLE
Add android background image support

### PR DESCRIPTION
**Pull request by ywongweb**
Added Android support for the `screenBackgroundImageName` feature from this PR wix#861

### CODE REVIEW

**Comment by fidlip** [comment]
This PR prevents my app from starting.

**Comment by ywongweb** [comment]
@fidlip My own app is using this PR and it's working fine. Can you check your logs and see if there are any clues on what happened?

**Comment by reyalpsirc** [comment]
@ywongweb this isn't working for me. I tested if the image was correctly set on drawable and it is because it loaded on my `createSplashLayout`. Anyway, the `screenBackgroundImageName` that have defined on the `navigatorStyle` for my screen containers is not working. Am I doing something wrong?

**Comment by ywongweb** [comment]
@reyalpsirc You need to set this at the root level 

```
  Navigation.startSingleScreenApp({
    screen: {
      screen: c.HOME,
    },
    appStyle: {
      orientation: 'portrait',
      screenBackgroundColor: 'transparent',
    },
  })
```

**Comment by ywongweb** [comment]
@reyalpsirc If you are using nest containers components, try setting it at the parent level.

Example
```
        <Container /* set navigatorStyle here */>
          <NestedContainer>
              ....
          </NestedContainer>
        </Container>
```

**Comment by reyalpsirc** [comment]
@ywongweb Thanks, its working now :) 👍

**Comment by reyalpsirc** [comment]
@ywongweb Sometimes I get a crash with this info:

captura de ecra 2017-11-14 as 23 47 24

Any idea why?

**Comment by filipef101** [comment]
This is not working in latest code, any idea why?

**Comment by ywongweb** [comment]
see new PR https://github.com/wix/react-native-navigation/pull/3051

**Comment by L-Yeiser** [comment]
This is still not working for me. I am on the latest version of of `react-native-navigation` V1 (1.1.476). I am setting the both `screenBackgroundImageName` and `rootBackgroundImageName` in the top level screen component. I have tried setting the navigator styles as a static property, in the constructor, in `componentDidMount`, and when I push the screen onto the stack. The image is accessible in my `drawable` folder.

**Pull request closed without merging**
