### PR TITLE
Fix mistake in platformSpecificDeprecated.ios

### PR DESCRIPTION
**Pull request by terrysahaidak**
There was issue: 

image

Seems like a mistake. Fixes by this PR.

### CODE REVIEW

**Comment by guyca** [comment]
Hey @terrysahaidak 
Can you please provide a bit more information on the issue? How did you reproduce it?

**Comment by terrysahaidak** [comment]
Hey, @guyca. Simply added `"react-native-navigation": "^2.0.0-experimental.304",` to my project. Installed it followed the instruction and build the app on iOS. On Android, it works good, but on iOS it throws an error after js initialized. I've run it with remote debugger with `stop on exception` flag.
It's stopped at the line I've changed.

This is an issue:
image

So, I've decided it simply was a mistake.

**Comment by terrysahaidak** [comment]
You can also test it by building my application on `tr-react-native-navigation` branch. [Link](https://github.com/terrysahaidak/GitterMobile/tree/tr-react-native-navigation)

**Comment by terrysahaidak** [comment]
Hey, @guyca. Could you reproduce and confirm that?

**Comment by guyca** [comment]
@terrysahaidak I'm not able to reproduce this error. Did you manage to reproduce it in the example app? Or create an example app where this is reproducible?

**Comment by terrysahaidak** [comment]
@guyca what version should I use now if 2.0.0.experimental is deprecated? I don't know which should I use to reproduce this error.

**Comment by terrysahaidak** [comment]
Oh, I see. If `Navigation.startSingleScreenApp({screen: {screen: { /* some screen */ }, passProps: { /* empty object */}}})`, `screen.passProps` is empty object it passes [this check](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.ios.js#L555). So I can close this PR. Thank you.

**Pull request closed without merging**
