### PR TITLE
[Android] Fix NoOpPromise to work for Android with RN 0.58

### PR DESCRIPTION
**Pull request by magnudae**
Fixes RNN on android with RN 0.58
Referring to discussion #4639

Solution by [joshperry131](/joshperry131)

Wanted to put this PR here to spark the discussion if this is a valid longterm solution or just a patch fix for now.

### CODE REVIEW

**Comment by retyui** [comment]
FIxed in https://github.com/wix/react-native-navigation/pull/4706

**Comment by denieler** [comment]
doesn't work for me with `"react-native": "0.58.4"`, `"react-native-navigation": "^2.10.0"`

**Comment by guyca** [comment]
Fix isn't published yet, will be available in 2.11.0

**Comment by magnudae** [comment]
@guyca awesome!

**Pull request closed without merging**
