### PR TITLE
[v2] Typings for styling options and layouts

### PR DESCRIPTION
**Pull request by birkir**
Added typings of all the configuration options and layouts.

 - [x] options
 - [x] options docs
 - [x] layout
 - [x] layout docs

They also include documentation in TSDoc format for autocomplete like this:

image

### CODE REVIEW

**Comment by guyca** [comment]
This's great! Can't wait ❤️

**Comment by birkir** [comment]
Work complete. Does not include any breaking changes, or actual code changes whatsoever.

Options are tagged iOS or Android if they are Platform specific.

It would be great to iterate on this and add code examples too (I added one for animations as a demo)

**Comment by birkir** [comment]
What was the issue? More failed tests?

**Comment by henrikra** [comment]
Can this be released? :)

**Comment by guyca** [comment]
@birkir It broke the Wix app apparently and we didn't have time to merge it back properly. I'm on vacation right now so don't have more information. When I get back, in two weeks, we'll get this back in.

**Comment by henrikra** [comment]
I wonder how it could break the app because it only adds types 🤔 Do you have idea why it broke? @birkir

**Comment by guyca** [comment]
@henrikra I think some optional fields were missing the `?` sign

**Pull request merged**
