### PR TITLE
Fixed TabBar from not adopting screen background color

### PR DESCRIPTION
**Pull request by BrendonSled**
[http://imgur.com/a/JTvwm](http://imgur.com/a/JTvwm)

### CODE REVIEW

**Comment by guyca** [comment]
Hey @BrendonSled 
If I understand correctly, this commit sets the entire Layout color to that of the current screen if tabs are hidden.
I'm not sure this is needed, user should define `drawUnderTabBar: true` if he intends to hide the `BottomTabs` or even better, RNN should stretch the `Screen` to fit the entire layout when tabs are hidden and `drawUnderTabBar === false`

**Comment by BrendonSled** [comment]
That should be the case @guyca but on screen transitions from `tabBarHidden: false` to a new screen with `tabBarHidden: true` there is a block under the tabs that is color mismatched. It's very easy to reproduce

**Comment by guyca** [comment]
Fair point @BrendonSled 👍

**Comment by spikeisryu** [comment]
I have the same issue. 
image

How can I resolve this issue?

react-native-navigation version is v1.1.152
react-native v0.45.1
and testing iOS

**Comment by jackmew** [comment]
The same issue In iOS.  I need to set tabBarTranslucent: true to solve this problem.

**Pull request merged**
