### PR TITLE
fix for breaking change in React Native 0.47

### PR DESCRIPTION
**Pull request by JPig**
fix for breaking change in React Native 0.47 the deprecated createJSModules Override

### CODE REVIEW

**Comment by JPig** [comment]
Not too sure why all the checks failed.

**Comment by JPig** [comment]
Seems the Tests Failing are totally unrelated to the PR upon actually checking the CI logs.

**Comment by DanielZlotin** [comment]
Thanks for the PR
why not remove this method alltogether?

**Comment by DanielZlotin** [comment]
additionally, if you checked that this is the only change needed for latest stable RN, if you can, please update `playground`'s `plackage.json` to use correct RN and react versions (along with dependencies) and update the yarn.lock

**Comment by JPig** [comment]
I could be wrong but i think the method needs to stay for backwards compatability?
And when i get a chance i can look into doing that.

**Comment by JPig** [comment]
just investigated it and removing the method all together causes issues for anything < 0.47. so i feel keeping the method would be best.

**Pull request merged**
