### PR TITLE
[iOS] Large title text attributes

### PR DESCRIPTION
**Pull request by eliperkins**
This adds support for changing `largeTitleTextAttributes` on navigation controllers, including custom font sizes, font families, etc.

See Apple docs here: https://developer.apple.com/documentation/uikit/uinavigationbar/2919946-largetitletextattributes 

Supports #2090 

Related to #1643

### CODE REVIEW

**Comment by anonrig** [comment]
What's the ETA on this PR? 👍

**Comment by brunolemos** [comment]
Needs rebase.

**Comment by eliperkins** [comment]
@brunolemos done

**Comment by sreuter** [comment]
Should this transform to a smaller title when scrolling up, like in the Mail example?

**Comment by DazChong** [comment]
I'm having screen bottom section of flickering if using largeTitle on iPhone X, the refreshControl and content jumped when pull-to-refresh, large title overlap refreshControl, and randomly scrolling to top stuck with no rubber-band effect and cannot pull-to-refresh.

**Pull request merged**
