### PR TITLE
Fix flickering BottomTabs when pushing a screen with waitForRender

### LINKED ISSUE #6381: BottomTabs flicker when push new screen using waitForRender (ANDROID) - (IOS Works well)
### Issue Description

When I'm going to open a new screen using waitForRender with true in the layout options the problem happens, but when I add waitForRender as false it opens normally, I need to use the waitForRender option as true because wait data load, does anyone know the reason for the problem?

### Steps to Reproduce / Code Snippets / Screenshots

waitForRender: true =>
wait-true

watForRender: false =>
wait-false

Code: 

`  ...options: {
        topBar:...,
        animations:{
          push: {
            waitForRender:true
          }
        }
      } `
---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?):ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?):both / all / both

### PR DESCRIPTION
**Pull request by guyca**
closes #6381

### CODE REVIEW

**Comment by iscosta** [comment]
path file: lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabs.java

```
public void enableItemsCreation() {
        itemsCreationEnabled = true;
        if (shouldCreateItems) {
            shouldCreateItems = false; //add
            createItems();
            forEach(onItemCreationEnabled, Runnable::run);
            onItemCreationEnabled.clear();
```

@guyca I added the informed value according to the code above in the correct file path, but the problem persists. anything else that should be done?

**Comment by guyca** [comment]
Did you recompile the code?

**Comment by iscosta** [comment]
@guyca Yes, I did recompile code and trying reinstall RNN to 6.9.1, but not solve problem :/  

Here is my code changed:

Captura de Tela 2020-07-16 às 14 48 23

Here is my sample code to push a new screen
Captura de Tela 2020-07-16 às 15 05 41

**Comment by guyca** [comment]
@iscosta Please clone the repo and reproduce in the playground app. If needed, push a reproduction to your fork.

**Comment by iscosta** [comment]
@guyca I reproduced the playground app and it worked correctly, I copied the bottomtabs file but it didn't work in my app, so I copied the full lib folder of the playground app and added it to my app, recompiled it through the android studio and it worked, I didn't understand why it didn't work the same process updating via npm, but after I copied the entire lib folder it worked.
Anyway I thank you very much for your help :)

**Pull request merged**
