### PR TITLE
[iOS] Fix getCurrentlyVisibleScreenId with drawer

### PR DESCRIPTION
**Pull request by Royce**
This fixes two issues with `Navigation.getCurrentlyVisibleScreenId` and `this.props.navigator.screenIsCurrentlyVisible()` on iOS.

- The wrong "controllerId" was being set for the initial screen/layout. `controllerId` is only used to return a `screenId` for Navigation.getCurrentlyVisibleScreenId.
- Take into account drawers, when trying to find the visible viewController.

### CODE REVIEW

**Comment by Royce** [comment]
Fixes #1728

**Comment by rynop** [comment]
@Royce `this.props.navigator.screenIsCurrentlyVisible()` is still always `false` for me on iOS.  react-native-navigation `v1.1.316`.  I'm not using drawer mode, I'm only using `Navigation.startTabBasedApp()`.

I've tried using `this.props.navigator.screenIsCurrentlyVisible()` both on a screen that is opened from a tab AND a screen that is opened in a modal.

Whats strange is calling `const visibleScreenInstanceId = await Navigation.getCurrentlyVisibleScreenId()` always returns a strange screen id like `controllerID1_nav0` instead of the screen ID that i registered via `Navigation.registerComponent('my.screen', () => ThingFinder, store, Provider);`

**Comment by Royce** [comment]
await Navigation.getCurrentlyVisibleScreenId() can't/won't return your
'my.screen'
because a 'my.screen' screen could be mounted multiple times. I don't
think await
Navigation.getCurrentlyVisibleScreenId() is really meant to be part of
the public API.

**Comment by rynop** [comment]
@Royce thanks makes sense. Shouldn't `this.props.navigator.screenIsCurrentlyVisible()` work though? (not always return `false`)?

**Pull request merged**
