### PR TITLE
Fix bottomTab truncated text on iPad

### LINKED ISSUE #6533: Tab bar text cut off and ellipsized on iPadOS 14
### Issue Description

When rendering a tab bar on an iPad running iPadOS Public Beta 6, text labels for tab bar items are truncated. 

### Steps to Reproduce / Code Snippets / Screenshots

IMG_0292

---
### Environment
* React Native Navigation version: Reproduced on playground app built from `master`
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS: iPadOS 14 Public Beta 6
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro 11" 2018

### PR DESCRIPTION
**Pull request by yogevbd**
Closes #6533

### CODE REVIEW

**Comment by guyca** [comment]
@yogevbd Seems like the two lines this PR deletes were added in b01629c. Are we certain this change won't cause regressions?

We gotta increase our screenshots coverage to cover BottomTabs as well. These iOS issues are madness.

**Comment by yogevbd** [comment]
The issue described in #6005 doesn't reproduce on iOS 14.2.
In this case where it's an iOS new feature bug, I'm not sure how screenshot tests will help but let's think about it..

**Review by guyca — APPROVED** [review]

**Comment by guyca** [comment]
We can use screenshot tests to ensure the tab item title isn't truncated in various font configuration.

**Comment by ryanbourneuk** [comment]
Hey @guyca & @yogevbd!

I've just updated to v7.8.1, and I've noticed on iOS 13.3 (iPhone 11 Pro simulator) my tab bar text is now truncated! With the changes in this PR reverted locally, they're fixed again. The iOS 14.2 (iPhone 12 Pro simulator) works with and without the lines being re-added.

I'm happy to `patch-package` this locally (as my client's project does not use text for tabs on iPad), but it may be worth investigating & resolving so both iPad and iPhone can show text.

Happy to help in any way I can, let me know if you need more details.

Thanks! 😄

**Comment by filipsuk** [comment]
I also had to use patch-package to revert this change. iPhone 8 simulator iOS 14.4 (and others) had issues with truncated text in the bottom menu.

**Pull request merged**
