### PR TITLE
[v3][android] Correcting the position of touch on overlay

### PR DESCRIPTION
**Pull request by minhtc**
Fix issue: https://github.com/wix/react-native-navigation/issues/5424

### CODE REVIEW

**Comment by fjmorant** [comment]
Anybody responsible for merging RNN, can we merge this? this solves mooost of our problems with touches in overlays.

Thanks

**Comment by ronhello** [comment]
Someone, please help to review this issue. Thanks

**Comment by Kamillpg** [comment]
Is anybody here? It's only `+4 -2` 🙏🏻but could save us ;)

**Comment by cenaHara** [comment]
not work with me

**Pull request closed without merging**
