### PR TITLE
[v2] making topbar icon configuration compatible on Android and iOS

### PR DESCRIPTION
**Pull request by emiyake**
Top bar's icon color configuration were different between iOS and Android.

On iOS
`{topBar: { backButton: {color: 'red' } } }` wasn't working.
`{topBar: { leftButtons: [{color: 'red'}] }` wasn't working either.

On the other hand: 
`{ topBar: { buttonColor: 'red'} }` was ignored on Android.

It works on both platforms now.

### CODE REVIEW

**Comment by ujwal-setlur** [comment]
This is great! Thanks! So what's the common syntax now?

**Comment by emiyake** [comment]
@ujwal-setlur  The common syntax would be:

```
     backButton: {
       icon: require('icon.png'),
       visible: true,
       color: 'green'
     }
````

```
{
  leftButtons: [
    {
      ...
      color: 'red'
    }
  ]
}
```

**Comment by emiyake** [comment]
@guyca Does this PR make sense?

**Comment by henrikra** [comment]
@emiyake Fix merge conflicts first?

**Pull request closed without merging**
