### PR TITLE
V3

### LINKED ISSUE #4005: [v2] Incorrect drawBehind behaviour while merging bottom tabs options
### Issue Description

I would like to hide the `bottomTabs` when keyboard shows on Android ([cause otherwise they appear on top of the keyboard](https://github.com/react-navigation/react-navigation-tabs/issues/16)) and show them again when keyboard hides. The solutions seems to be toggling `bottomTabs.visible` but it seems like the tabs disappear but a white container stays there. Setting `bottomTabs.drawBehind: true` with `setDefaultOptions` fixes it but I'd like to toggle `drawBehind` like in the code below and this doesn't work. Looks like `drawBehind` is not taken into account in `mergeOptions`.

### Steps to Reproduce / Code Snippets / Screenshots

```
  Navigation.setDefaultOptions({
    bottomTabs: {
      visible: true,
      animate: false,
      drawBehind: false,
    },
  });
```
```
    Keyboard.addListener(
      'keyboardDidShow',
      () =>
        Platform.OS === 'android' &&
        Navigation.mergeOptions('BottomTabsId', {
          bottomTabs: {
            visible: false,
            drawBehind: true,
          },
        })
    );
    Keyboard.addListener(
      'keyboardDidHide',
      () =>
        Platform.OS === 'android' &&
        Navigation.mergeOptions('BottomTabsId', {
          bottomTabs: {
            visible: true,
            drawBehind: false,
          },
        })
    );

```

screen shot 2018-09-20 at 15 42 44

---
#

## Environment
* React Native Navigation version: 2.0.2544
* React Native version: 0.55.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s 11.4.1 debug mode

### LINKED ISSUE #5228: v3 alpha [05/08 alpha.11 published]
# 3.0.0-alpha.11

# Changes
- [x] Support RN 0.60
- [x] Migrate to AndroidX
- [x] Improve draw behind StatusBar (Preparation for #4258)
- [x] Don't push BottomTabs when keyboard is displayed (Fixes #4005, #3424)
        - It won't be needed to toggle the BottomTabs when Keyboard is visible
- [x] BottomTab badge and dot indicator are not animated by default on Android (parity with iOS)

# Updating from v2
v3 is currently in alpha. To update simply npm install `3.0.0-alpha.11` - `npm install --save react-native-navigation@3.0.0-alpha.11`.
Breaking changes are outlined below.

## Layout system changes on **Android**
* Parent layouts (BottomsTabs, Stack, SideMenu) are always laid out behind the StatusBar.
* Components (`component` and `externalComponent`) are measured and offset according to the StatusBar.

In this release, We're changing the layout system in order to provide better support for immersive and full screen apps. In this release we've improved support for drawing behind the StatusBar,  next we'll address drawing behind the NavigationBar. 

Use the `drawBehind` and `translucent` options to control the StatusBar
```js
statusBar: {
  drawBehind: true,  // will draw a screen behind the StatusBar
  translucent: true // Usually you'll want to have drawBehind: true when this is true
}
```

While this isn't a breaking API change - there are a few breaking side effects.

### How will my app be effected
1. When the keyboard is opened, BottomTabs will now be drawn behind the keyboard and won't shift upwards. This is in parity with the current behaviour in iOS. For the most part, this isn't a breaking change. Toggling BottomTabs when TextInput's focus changes won't be needed anymore.

2. **Update:** Fixed in `3.0.0-alpha.1`
~~If you've specified a **custom** TopBar animation which animates `y` or `translationY` properties, you'll need to compensate for the TopBar's topMargin. **This is a temporary solution and will be addressed in one of the next alpha releases.**~~
For example:
```js
const statusBarHeight = getStatusBarHeight();
const topBarHeight = getTopBarHeight();
...
pop: {
  topBar: {
    enabled: true,
    y: {
      duration: 300,
      from: statusBarHeight,
      to: -topBarHeight + statusBarHeight
    }
  }
}
```

3. While parent controllers are drawn behind the StatusBar, their background isn't.
This means that when transitioning from a destinations drawn under the StatusBar to a destination drawn behind it, the application's default background color will be visible behind the StatusBar.
If you application's theme is dark, you might want to change the `windowBackground` property to mitigate this:

Add the following to your application's `style.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@color/backgroundColor</item>
    </style>

    <!--This is your application's default background color.
    It will be visible when the app is first opened (while the splash layout is visible)
    and when transitioning between a destination a screen drawn under the StatusBar to
    a destination drawn behind it-->
    <item name="backgroundColor" type="color">#f00</item>
</resources>
```

## AndroidX migration
We've migrated RNN to AndroidX, please follow migration instructions in the react-native repo.

## Removed SyncUiImplementation
[SyncUiImplementation](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/reactNative57WixFork/java/com/reactnativenavigation/react/SyncUiImplementation.java) was used to overcome a bug in RN's UiImplementation. This workaround was added to RN's `UiImplementation` in RN 0.60 (thanks @SudoPlz) and can be removed from RNN.

If you're using `SyncUiImplementation` your app will fail to compile after upgrading to v3. Simply remove the following code from your `MainApplication.java`
```diff
- import com.facebook.react.uimanager.UIImplementationProvider;
- import com.reactnativenavigation.react.SyncUiImplementation;


- @Override
- protected UIImplementationProvider getUIImplementationProvider() {
-     return new SyncUiImplementation.Provider();
- }
```

## BottomTab badge and dot indicator are not animated by default on Android (parity with iOS)
Showing and hiding badge and dot indicator are now not animated by default. Badge animation is now controlled with the `bottomTab.animateBadge` property and dot indicator with `bottomTab.dotIndicator.animate` property.

#### The following option will show a badge with animation
```js
bottomTab: {
  badge: 'new,
  animateBadge: true
}
```

#### The following option will show a dot indicator with animation
```js
bottomTab: {
  dotIndicator: {
    visible: true,
    animate: true
  }
}
```

### PR DESCRIPTION
**Pull request by guyca**
# Changes
* Support RN 0.60
* Migrate to AndroidX
* Improve draw behind StatusBar (Preparation for #4258)
* Don't push BottomTabs when keyboard is displayed (Fixes #4005, #3424)
    - It won't be needed to toggle the BottomTabs when Keyboard is visible
* BottomTab badge and dot indicator are not animated by default on Android (parity with iOS)

# Updating from v2
v3 is currently in alpha. To update simply npm install `3.0.0-alpha.11` - `npm install --save react-native-navigation@3.0.0-alpha.11`.
Breaking changes are outlined below.

## Layout system changes on **Android**
* Parent layouts (BottomsTabs, Stack, SideMenu) are always laid out behind the StatusBar.
* Components (`component` and `externalComponent`) are measured and offset according to the StatusBar.

In this release, We're changing the layout system in order to provide better support for immersive and full screen apps. In this release we've improved support for drawing behind the StatusBar,  next we'll address drawing behind the NavigationBar. 

Use the `drawBehind` and `translucent` options to control the StatusBar
```js
statusBar: {
  drawBehind: true,  // will draw a screen behind the StatusBar
  translucent: true // Usually you'll want to have drawBehind: true when this is true
}
```

While this isn't a breaking API change - there are a few breaking side effects.

### How will my app be effected
1. When the keyboard is opened, BottomTabs will now be drawn behind the keyboard and won't shift upwards. This is in parity with the current behaviour in iOS. For the most part, this isn't a breaking change. Toggling BottomTabs when TextInput's focus changes won't be needed anymore.

2. While parent controllers are drawn behind the StatusBar, their background isn't.
This means that when transitioning from a destinations drawn under the StatusBar to a destination drawn behind it, the application's default background color will be visible behind the StatusBar.
If you application's theme is dark, you might want to change the `windowBackground` property to mitigate this:

Add the following to your application's `style.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@color/backgroundColor</item>
    </style>

    <!--This is your application's default background color.
    It will be visible when the app is first opened (while the splash layout is visible)
    and when transitioning between a destination a screen drawn under the StatusBar to
    a destination drawn behind it-->
    <item name="backgroundColor" type="color">#f00</item>
</resources>
```

## AndroidX migration
We've migrated RNN to AndroidX, please follow migration instructions in the react-native repo.

## Removed SyncUiImplementation
[SyncUiImplementation](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/reactNative57WixFork/java/com/reactnativenavigation/react/SyncUiImplementation.java) was used to overcome a bug in RN's UiImplementation. This workaround was added to RN's `UiImplementation` in RN 0.60 (thanks @SudoPlz) and can be removed from RNN.

If you're using `SyncUiImplementation` your app will fail to compile after upgrading to v3. Simply remove the following code from your `MainApplication.java`
```diff
- import com.facebook.react.uimanager.UIImplementationProvider;
- import com.reactnativenavigation.react.SyncUiImplementation;


- @Override
- protected UIImplementationProvider getUIImplementationProvider() {
-     return new SyncUiImplementation.Provider();
- }
```

## BottomTab badge and dot indicator are not animated by default on Android (parity with iOS)
Showing and hiding badge and dot indicator are now not animated by default. Badge animation is now controlled with the `bottomTab.animateBadge` property and dot indicator with `bottomTab.dotIndicator.animate` property.

#### The following option will show a badge with animation
```js
bottomTab: {
  badge: 'new,
  animateBadge: true
}
```

#### The following option will show a dot indicator with animation
```js
bottomTab: {
  dotIndicator: {
    visible: true,
    animate: true
  }
}
```

closes #5228

### CODE REVIEW

**Comment by SudoPlz** [comment]
Goooooood job there!!

**Comment by mayconmesquita** [comment]
@guyca great job!!!

**Comment by toomass** [comment]
I notice that the initial post mentions next addressing the "NavigationBar."  Is there a sense of the timing for this?  As far as I can tell there is not an option in v3 to hide the Android system screen navigation and display extended app content.  Unless I'm missing something?  Thanks!

**Comment by guyca** [comment]
RNN currently doesn't fully support immersive mode on Android. The motivation is that with the new gesture navigation introduced in Android 10 full screen apps will probably be more common.
Indeed, v3 doesn't support drawing behind the navigation bar, but it contains the features needed for it.

**Comment by toomass** [comment]
Hi Guy,

While I understand your comment generally, whenever I put my app into an immersive mode for android through code in MainActivity, I seem to wind up with a blank area for the navigation bars (and notch area) for android x and otherwise phones.  Is that expected?  I'm not really sure how I would get the RNN to recognize my app as fullscreen? Thanks for any guidance.

Tom

**Comment by sampsonjoliver** [comment]
I'm also curious on the NavigationBar timeline. Our team has a similar usecase where we are seeing the "blank area" issue, and need RNN to factor this in during its layout.

**Pull request merged**
