### PR TITLE
Add a way to dynamically enable/disable a side menu for Android

### LINKED ISSUE #326: How disable drawer on current window?
### Issue Description

How disable drawer on current window?

---
### Environment
- React Native Navigation version: 2.0.0-experimental.120
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): both

### PR DESCRIPTION
**Pull request by MattDavies**
Fixes #326 for Android only - I looked at the props approach but I needed a bit more control than I could get with that.

Sidenote: I'll need to do similar for iOS, but that looks a bit tricker given the multiple different drawer implementations (and the first implementation I looked at didn't have a clean way to disable without removing the view completely).

### CODE REVIEW

**Comment by guyca** [comment]
@MattDavies looks good. Can we document this method here https://wix.github.io/react-native-navigation/#/screen-api ? Otherwise this will get left out of the next version

**Comment by MattDavies** [comment]
@guyca Done. Hadn't seen the new docs, they are looking amazing. Nice work!

**Comment by guyca** [comment]
Merged, thanks!

**Comment by Fenwil** [comment]
Thanks for the work @MattDavies and @guyca !! 

I will leave the link here: http://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-android-only

**Pull request merged**
