### PR TITLE
[v2] fix bridge reload issue

### PR DESCRIPTION
**Pull request by joonhocho**
https://github.com/wix/react-native-navigation/issues/1514
There could be better solution than this, but I think it's good enough for now.

### CODE REVIEW

**Comment by rustybox** [comment]
I really don't think this is good enough, that's why I made a comment instead of a pull request.

If this is to be merged in it should probably note the hack in a comment so someone can take a look in the future.

**Comment by joonhocho** [comment]
@rustybox I agree. Added TODO comment. I still think it's 10x better than nothing since you can't reload without this.

**Comment by suren1525** [comment]
It work for me too.

**Comment by jslz** [comment]
hi, how do we follow which release commits get into? Are these fixes in 1.1.x versions or only 2.x versions? Thanks.

**Pull request closed without merging**
