### PR TITLE
Fix nullable dispatcher of modals on Android

### PR DESCRIPTION
**Pull request by svbutko**
This should be hot fixed since production build fails.
Fixes: #7285

### CODE REVIEW

**Comment by kr4ckhe4d** [comment]
I was just going to make a pull request. Thanks

Not a great day for RNN today heh

**Comment by svbutko** [comment]
> I was just going to make a pull request. Thanks
> 
> 
> 
> Not a great day for RNN today heh

Good thing that it was found early and shows flaws in CI/CD pipeline which will be fixed because of it

**Comment by swabbass** [comment]
It happens when using RN 66 is not already supported in v7....v8 has RN 66 and this can be merged there..you can do `?` in master it will throw warning until RN is updated to RN66

**Comment by svbutko** [comment]
> It happens when using RN 66 is not already supported in v7....v8 has RN 66 and this can be merged there..you can do `?` in master it will throw warning until RN is updated to RN66

I think we should merge this to master together with #7286 ship a minor release, and then focus on v8, since RN64 branch is already on RN66 we can adjust CI/CD and do merge other stuff from 8.0.0 milestone

**Review by swabbass — APPROVED** [review]
Soon v8 will be ready Thanks to you!

**Pull request merged**
