### PR TITLE
pass imageInsets for tab icon [iOS]

### PR DESCRIPTION
**Pull request by gevorg94**
You can pass ImageInsets for tab bar icon(You can center tab icon when there is no title).
```js
const TABS = [
  {
    screen: 'screen1',
    icon: require('img/icon1.png'),
    selectedIcon: require('img/icon1_selected.png'),
    navigatorStyle: {
      navBarHidden: true
    },
    iconInsets: {
      top: 6,
      left: 0,
      bottom: -6,
      right: 0,
    }
  },
  {
    screen: 'scene2',
    icon: require('img/icon2.png'),
    selectedIcon: require('img/icon2_selected.png'),
    navigatorStyle: {
      navBarHidden: true,
    },
    iconInsets: {
      top: 6,
      left: 0,
      bottom: 0,
      right: 3,
    }
  }
]
```

### CODE REVIEW

**Comment by shahen94** [comment]
screen shot 2017-04-26 at 1 11 38 pm

**Comment by guyca** [comment]
Hey @gevorg94 Thanks for the pr! Two minor comments:
1. please rename `imageInsets` to `iconInsets`
2. add the new property to the [docs](https://wix.github.io/react-native-navigation/#/top-level-api)

👍

**Comment by gevorg94** [comment]
@guyca i've changed it. is this ok?

**Comment by guyca** [comment]
looks great 👍

**Pull request merged**
