### PR TITLE
added tabBarHidden property to navigatorStyle

### PR DESCRIPTION
**Pull request by alinz**
In ios `tabBarHidden` is not working and required bunch of js hack to getting the desire thing to work. Based on my observation `tabBarHidden` was never implemented for navigatorStyle and I simply added that functionality.

### CODE REVIEW

**Comment by MrLoh** [comment]
It would be awesome if this could be merged. It's really annoying to have to hide the tab bar in componentWillMount and produces a weird flickering of the tab bar being briefly visible.

**Comment by guyca** [comment]
Hey @alinz 
Thanks for the PR. Can you please describe the use case when `tabBarHidden` doesn't work for you?
I think there's an issue when it's defined in `navigatorStyle` of the first tab. Is this the use case your pr addresses?

**Comment by MrLoh** [comment]
That's what he said here: https://github.com/wix/react-native-navigation/issues/1384#issuecomment-329820364

**Comment by MrLoh** [comment]
I have an app that encounters that issue. I can give it a try wether this actually fixes it.

**Comment by gran33** [comment]
Thanks for this man. 😘

**Pull request merged**
