### PR TITLE
Add dependency injection

### PR DESCRIPTION
**Pull request by henrikra**
## What this PR does?

This library heavily doing OOP in the codebase on TS side which is great! What was not so great is the dependency handling. As you can see from the `Navigation.ts` it created all the dependencies which isn't its job. Also that file wasn't testable because it created all the dependencies.

## What has changed

I added library called typedi which is meant for dependency injecting with TS and JS! In typedi you just mark a service class with `@Service(<serviceNameHere>)` and then you can inject to any other service using `@Inject(<serviceNameHere>)`! Very handy! These principles are coming from Java and other OOP languages.

## Opinions?

Tell me what do you guys think? I think the code functions now as it should when thinking in terms of OOP ☕️

### CODE REVIEW

**Comment by henrikra** [comment]
@guyca @yogevbd What do you guys think about this? 🎉

**Comment by guyca** [comment]
Hey @henrikra !
Thanks for the PR and sorry for not replying sooner.

My feelings towards this pr are a bit ambivalent. On the one hand one could argue about the benefits of DI, but on the other hand there's no denying the risk introduced by another dependency to this _library_, especially one which relies on stage 2 and experimental TS features.

Looking at the diff, the code base definitely looks cleaner, `Navigation.ts` especially, and future refactors might be easier and more contained thanks to this. Unfortunately I think the added risk is not worth it.

I actually don't think there's anything wrong with how RNN currently does DI - injecting dependencies in constructor is pretty straight forward.

lets keep this an open discussion, hopefully other members can void their opinions as well.

**Comment by hannta** [comment]
Nice, `Navigation.ts` looks a lot of cleaner now.

Dependency injection might not be the most popular pattern on JS/TS projects, but that does not make it any worse.

**Comment by henrikra** [comment]
@guyca How are your feelings now towards this? :)

**Pull request closed without merging**
