### PR TITLE
Register passProps in PropsRegistry for showInAppNotification for Android

### PR DESCRIPTION
**Pull request by varungupta85**

### CODE REVIEW

**Comment by varungupta85** [comment]
I apologize for my limited git knowledge. In this PR, only one commit `Register passProps in PropsRegistry for showInAppNotification for Android` is meaningful. The previous commits are already merged into the master branch by @guyca. Is there a way to remove these unneeded commits messages from the PR.

**Comment by Royce** [comment]
@varungupta85  There is way to clean up the PR. It involves creating new branch of upstream/master and then creating a new PR. It's not too hard. I sent you a message (in discord) with the steps.

**Comment by guyca** [comment]
Thanks a lot @Royce and @varungupta85

**Comment by varungupta85** [comment]
Thanks @Royce. Will create a new PR without the unnecessary commit messages.

**Pull request closed without merging**
