### PR TITLE
Add sideMenu.openGestureMode option

### PR DESCRIPTION
**Pull request by yogevbd**
Until now controlling drawers touch gestures was impossible, drawers received gesture opening touch from the entire screen and that causes collisions with other gestures (which are implemented on the javascript side).

This commit adding modes for how sideMenu drawers gestures will receive opening touch.
```
{
  sideMenu: {
    openGestureMode: 'entireScreen' | 'bezel'
  }
}
```

- `entireScreen`: drawer gesture will trigger drawer opening from the entire screen
- `bezel`: drawer gesture will trigger drawer opening only from the center screen bezel frame

The default didn't change.

### CODE REVIEW

**Comment by henrikra** [comment]
What has happened since nothing has been merged in over 20 days? 🤔

**Comment by henrikra** [comment]
Good to hear!

**Comment by pkyeck** [comment]
can anyone please look at the code I posted and tell me why this isn't working? ☝️

**Comment by alexxsanchezm** [comment]
> can anyone please look at the code I posted and tell me why this isn't working? ☝️

Maybe something like this
````
root: {
    sideMenu: {
        center: { ..... },
        left: { ...... },
        options: {
            sideMenu: {
                openGestureMode: 'bezel',
                // other options....
            }
        }
    }
}
````

**Pull request merged**
