### PR TITLE
Fix blank screen when resume app on Android

### PR DESCRIPTION
**Pull request by minhtc**

### CODE REVIEW

**Comment by tamdesktop** [comment]
thanks @minhtc 
Your PR save my life

**Comment by adurandet** [comment]
Hi guys,

Is there any reason this hasn't been merged?

**Comment by guyca** [comment]
Commit 5c266e4 basically does the same thing

**Comment by adurandet** [comment]
Thanks :)

**Comment by LingboTang** [comment]
I'm still having this issue

**Comment by andrewsadowski** [comment]
I've noticed that this is an issue with Android 8 and below, but does not affect Android 9.

**Pull request closed without merging**
