### PR TITLE
fix iOS11 safeArea

### PR DESCRIPTION
**Pull request by gran33**
https://github.com/wix/react-native-navigation/issues/1858

### CODE REVIEW

**Comment by DanielZlotin** [comment]
@gran33 do that in v2 as well?

**Comment by gran33** [comment]
@DanielZlotin Open an issue :)

**Comment by LeoNatan** [comment]
This is not the correct solution.

**Comment by LeoNatan** [comment]
Fixed in v2. Will back-port to v1.

**Pull request merged**
