### PR TITLE
Expose onConfigurationChanged in ActivityCallbacks.

### PR DESCRIPTION
**Pull request by ruiaraujo**
I need it to integrate https://github.com/yamill/react-native-orientation.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
Thanks for the fast merge.

**Comment by guyca** [comment]
Sure, thanks a lot for the contribution! 👍

**Comment by andrerfneves** [comment]
@guyca or @ruiaraujo I'm running into issues while integrating the `react-native-orientation` package with RNN myself. Not entirely sure why but I keep running into `error: method does not override or implement a method from a supertype: @Override` and `this.sendBroadcast(intent)` inside of `onConfigurationChanged` method. Here's what I'm trying to do:

### MainApplication.java
``` java
  @Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics());
    SoLoader.init(this, /* native exopackage */ false);

    registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
      @Override
      public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
        SplashScreen.show(activity);
      }

      @Override
      public void onActivityStarted(Activity activity) {}

      @Override
      public void onActivityResumed(Activity activity) {}

      @Override
      public void onActivityPaused(Activity activity) {}

      @Override
      public void onActivityStopped(Activity activity) {}

      @Override
      public void onActivitySaveInstanceState(Activity activity, Bundle outState) {}

      @Override
      public void onActivityDestroyed(Activity activity) {}
    });
  }
}
``` 

Any help would be greatly appreciated!

**Comment by rawrmaan** [comment]
@andrerfneves Similar issue here. Make sure you update your `react-native-navigation` and `react-native-orientation` to the latest versions to get around the `error: method does not override or implement a method from a supertype: @Override` problem--that has to do with a breaking change in RN 0.47.

It looks like `NavigationApplication` doesn't expose `this.setBroadcast`, so someone who's good and Android dev is going to need to implement that in the proper way before we can get this working.

**Comment by rawrmaan** [comment]
Okay, I figured it out--instead of `this.sendBroadcast(intent)`, just write `sendBroadcast(intent)`! My limited understanding of Java hasn't failed me!

**Comment by andrerfneves** [comment]
Thanks @rawrmaan, I'll give that a try!

**Comment by MrLoh** [comment]
@rawrmaan @ruiaraujo I can't get this to work, I have no experience with Android and I can't find any explanation of how to get it to work. From the above example I get errors in two places

```java
@Override // ERROR: method does not override method from it's super class
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig); // ERROR: Cannot resolve method
    Intent intent = new Intent("onConfigurationChanged");
    intent.putExtra("newConfig", newConfig);
    sendBroadcast(intent);
}
```

**Comment by rawrmaan** [comment]
@MrLoh Are you writing that code inside `setActivityCallbacks(new ActivityCallbacks() { ... }` in your `onCreate` function of your `MainApplication`, which extends `NavigationApplication`? Because that's where it should go. Full example:

```java
public class MainApplication extends NavigationApplication implements ReactApplication {
  @Override
  public void onCreate() {
    super.onCreate();

    setActivityCallbacks(new ActivityCallbacks() {
      @Override
      public void onConfigurationChanged(Configuration newConfig) {
         super.onConfigurationChanged(newConfig);
         Intent intent = new Intent("onConfigurationChanged");
         intent.putExtra("newConfig", newConfig);
         sendBroadcast(intent);
      }
    });
  }
}
```

**Comment by MrLoh** [comment]
no, I had this inside `registerActivityLifecycleCallbacks` now I don't get errors anymore. But the Orientation listener still doesn't fire on the javascript side

**Comment by rawrmaan** [comment]
@MrLoh Make sure you also update your `AndroidManifest.xml` with `      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"` on your `<activity>`.

**Comment by MrLoh** [comment]
yep, it's working now. Thank's a lot. Only calling `lockToLandscape` doesn't work. The method is called on the android part, but the orientation doesn't get locked.

**Pull request merged**
