### PR TITLE
Update sharedElementTransition.ios.js

### PR DESCRIPTION
**Pull request by tolu360**
Fix missing import of PropTypes throwing an error on iOS

### CODE REVIEW

**Comment by guyca** [comment]
Thanks @tolu360

**Comment by zwenza** [comment]
this will not work with react 16.0 because the prop-types package was moved out of react

**Comment by tolu360** [comment]
Hi @zwenza, was the move done after `16.0.0-alpha.6`?

**Comment by zwenza** [comment]
i don't exactly know if the alpha6 already removed it but the final 16.0 will remove it as far as i know

**Comment by tolu360** [comment]
Still works in alpha 6, moving forward, what would be the right way to use PropTypes?

**Comment by zwenza** [comment]
okay then it's fine. The right way would be to add the new prop-types package (https://www.npmjs.com/package/prop-types) and use it with `import PropTypes from 'prop-types'` and then use it just like before.

**Comment by tolu360** [comment]
Alright, noted.

**Pull request merged**
