### PR TITLE
SetStyle fix

### PR DESCRIPTION
**Pull request by yogevbd**
@danielang Removing changes in RCCNavigationController fixed the issue we had. Does this make sense?

### CODE REVIEW

**Comment by danielang** [comment]
I've add this changes because if you don't update all `viewControllers` in the stack of the screen they won't update their styles when you pop them: the tabbar stays in their previous color, etc.

**Comment by yogevbd** [comment]
@danielang The problem is that all viewControllers in UINavigationController stack will call `updateStyle` on `setStyle`. It causes styles that affect UINavigationBar to be applied multiple times (like `navBarHidden`).
I think moving tabBarItem styles to `setStyleOnInit` will solve this.

**Comment by danielang** [comment]
@yogevbd: by the naming convention of the method `setStyleOnInit` I thought that this method would only called once while the viewController is initializing.
So how the viewController will be notified when the style of the tabbar has been changed?

**Comment by danielang** [comment]
@yogevbd any reaction? 🙂

**Comment by guyca** [comment]
The feature your PR implemented is updating BottomTabs (tabBar) style by calling `setStyle` - @danielang can you confirm this PR covers the use cases you had in mind?

**Comment by danielang** [comment]
@guyca: Yes, of cause.
But it seems that @yogevbd  has discovered an 'bug' in iOS that the naviationbar will be updated too often while transitioning between screens; so it produces some lags.
I couldn't verfiy it in my simulator. And we've began a discussion about a better implementation. And now I am waiting for a response.

**Comment by yogevbd** [comment]
@danielang What I had in mind is to implement another function that handled all tabItem styles and call it every time just like setStyleOnInit.

**Pull request merged**
