### PR TITLE
added title and subtitle testIds

### LINKED ISSUE #7879: Title and subtitle test ID's
### Describe your idea

Feature request by @Niryo
While the top-bar's top container can have a test ID, there are no matchers for inherent sub-elements such as the title and subtitle (button can be set with proprietary test ID's). We need a means by which the title and subtitle would have a test ID, whether being set explicitly or implicitly by inheriting from the top-bar container's.

### Motivation

_No response_

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [X] No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by Niryo**
Fixes #7879

### CODE REVIEW

**Comment by d4vidi** [comment]
Thanks dude! We're planning on follow up on that right after the holidays. I hope it's alright.

**Comment by Niryo** [comment]
@d4vidi can you take this?

**Comment by d4vidi** [comment]
> @d4vidi can you take this?

Yeah I'll take it in this sprint or the next one

**Review by asafkorem — APPROVED** [review]

**Comment by d4vidi** [comment]
@Niryo Release in 7.40.0

**Pull request merged**
