### PR TITLE
fix(iOS): implement `scaleX` and `scaleY` transition animations.

### LINKED ISSUE #7066: setRoot animations don't work on iOS, was it designed that way?
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: FILL THIS OUT
- React Native version: FILL THIS OUT
- Platform(s) (iOS, Android, or both?): FILL THIS OUT
- Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### PR DESCRIPTION
**Pull request by oblador**
I was tearing my hair over why I couldn't get scale transitions to work on iOS while they were working fine on Android, and it turns out it was never implemented 😅 

This PR adds this implementation. 

Fixes #7066

### CODE REVIEW

**Comment by oblador** [comment]
Not sure about the failing tests, seems unrelated `write error: No space left on device`

**Comment by oblador** [comment]
Bad bot

**Comment by oblador** [comment]
@asafkorem Any chance this could get some eyes on it?

**Comment by asafkorem** [comment]
Yes @oblador, I'll review it later this week

**Review by asafkorem — APPROVED** [review]
Thanks a lot for this contribution @oblador, great work! 💯

**Comment by asafkorem** [comment]
Sure @oblador

**Pull request merged**
