### PR TITLE
[v2] [iOS] Back button: Allow for both icon and title, use topbar title attributes

### PR DESCRIPTION
**Pull request by kyle-ssg**
I'm not an Objective C developer, but this solves an issue I'm currently seeing.

1 - You can't have custom back icon with title, in this scenario it will only render the icon

2- Setting the topbar font has no affect on the back button title

After: Back has both custom font and icon, back button title renders next to icon

Also, tiny nit but this also removes some trailing spaces.

### CODE REVIEW

**Comment by guyca** [comment]
Seems like one unit test is failing
```
19:08:38 /Users/jenkins/.jenkins/workspace/rnn-ios-pr/lib/ios/ReactNativeNavigationTests/UINavigationController+RNNOptionsTest.m:38: error: -[UINavigationController_RNNOptionsTest testSetBackButtonIcon_withColor_shouldSetIcon] : ((icon) equal to (viewController.navigationItem.backBarButtonItem.image)) failed: ("<5023d723 eb7f0000>") is not equal to ("<00000000 00000000>")
```

**Comment by kyle-ssg** [comment]
I'll take a look, I imagine it'll be quite straight forward to update.

It seems like the android side isn't able to have both an icon and text too for the back button, was this done by design @guyca ?

**Comment by guyca** [comment]
Currently thats not supported as it's not a common Android pattern.

**Comment by kyle-ssg** [comment]
Duh of course, because of the navbar title positioning :D, think for iOS through the above is definitely a pattern so this change has some value. OK, will fix the tests up.

**Comment by guyca** [comment]
@kyle-ssg Sounds good, if you run into issues with the tests let us know.

**Comment by kyle-ssg** [comment]
Snowed under atm, aiming to do this on the weekend. Sidenote, this PR also fixes custom back button positions - it's further right than normal before this change.

**Comment by lukebrandonfarrell** [comment]
Any update on this @guyca @kyle-ssg ? 

Does it just need to be rebased and tests fixed on Android? if so I can give it a shot.

**Pull request closed without merging**
