### PR TITLE
Update custom RctManager to use old bridge

### PR DESCRIPTION
**Pull request by earaujoassis**
This error was reported in Android (API 23), React Native 0.30.
https://github.com/facebook/react-native/issues/8701

### CODE REVIEW

**Comment by beast** [comment]
This works well. Solved my problem when I upgraded to RN0.30.

**Comment by guyca** [comment]
@earaujoassis Thanks for the PR. This change will break the app for users who haven't upgraded to RN 0.30, So we can't accept it yet.
Once we switch to RN 0.30, or higher, we'll address this issue.
Thanks

**Comment by edvinasbartkus** [comment]
👍

**Comment by DanielMaly** [comment]
Is this still planned for merging into version 2.0?

**Comment by guyca** [comment]
@DanielMaly We're still developing v2.0 - once it stabilizes we will upgrade to the latest react version. But while we're still working on v2.0 we can't support versions above 0.25.1

**Comment by DanielZlotin** [comment]
An upgrade to RN31 is scheduled for v2.0.0, soon.

**Pull request closed without merging**
