### PR TITLE
this.props.navigator is undefined

### PR DESCRIPTION
**Pull request by dabit1**

### CODE REVIEW

**Comment by guyca** [comment]
Hey @dabit1 
Can you please explain the reason for this change? the navigator is injected to props, shouldn't be undefined.

**Comment by dabit1** [comment]
Yes, sorry. The undefined is `this.props` because you are in constructor() that can't access to `props` via `this`. It has to access via `props` without `this`.

**Comment by DanielZlotin** [comment]
probably not calling `super(props)` in the constructor

**Comment by guyca** [comment]
@dabit1 props are injected in the constructor, if you're calling `super(props` they shouldn't be null.
I'm closing for now, but let me know if I misunderstood the issue or if the docs are not clear enough on this matter.

**Comment by dabit1** [comment]
You are right.. sorry I was wrong.

**Pull request closed without merging**
