### PR TITLE
Close modal button

### PR DESCRIPTION
**Pull request by fvonhoven**
When playing with the example app, I noticed there wasn't a clear way to close the Modal example screen in iOS. This adds a button to dispatch `dismissModal()` and close the modal for iPhone.

### iOS
react-native-navigation - close modal

### CODE REVIEW

**Comment by witalobenicio** [comment]
Is this already available in production?

**Comment by fvonhoven** [comment]
Not that I know of.

**Comment by witalobenicio** [comment]
@fvonhoven I was not able to replicate your code in my project. It says that navigator doesn't have a dismissModal function

**Comment by smooJitter** [comment]
@fvonhoven I'm getting the same error as @witalobenicio

**Comment by fvonhoven** [comment]
@witalobenicio and @smooJitter can you paste your Modal.js code here?

**Comment by smooJitter** [comment]
I didn't change the code at all.  It's a bit odd, nevertheless it was interesting to see how the component picked up geolocation object.. 
 ```
const CloseModalButton = ({text}) =>
<TouchableOpacity
  style={[styles.buttonContainer]}
  onPress={() => navigator.dismissModal()}
>
  <View style={styles.closeModalButton}>
    <Text style={styles.buttonText}>{text}</Text>
  </View>
</TouchableOpacity>;
Navigation.registerComponent('CloseModalButton', () => CloseModalButton);

class Modal extends Component {
  static navigatorButtons = {
    rightButtons: [
      {
        id: 'close-modal-button',
        component: Platform.OS === 'ios' ? 'CloseModalButton' : null,
        passProps: {
          text: 'Close'
        }
      }
    ]
  };

  componentWillMount() {
    navigator = this.props.navigator;
  }

  onPushScreen = () => {
    this.props.navigator.push({
      screen: 'example.Types.Modal',
      title: `Screen ${this.props.count || 1}`,
      passProps: {
        count: this.props.count ? this.props.count + 1 : 2
      }
    });
  };

  onResetTo = () => {
    this.props.navigator.resetTo({
      screen: 'example.Types.Modal',
      icon: require('../../../img/list.png'),
      title: 'Modal'
    });
  };

  onPopToRoot = () => {
    this.props.navigator.popToRoot();
  };

  render() {
    return (
      <View style={styles.container}>
        <Text>Modal Screen</Text>
        <View style={styles.button}>
          <Button
            onPress={this.onPushScreen}
            title="Push Screen"/>
        </View>
        <View style={styles.button}>
          <Button
            onPress={this.onResetTo}
            title="Reset Stack"/>
        </View>
        {this.props.count > 1 && <View style={styles.button}>
          <Button
            onPress={this.onPopToRoot}
            title="Pop To Root"/>
        </View>}
      </View>
    );
  }
}
```

**Pull request merged**
