### PR TITLE
fix defaultOptions not respected on Android (#5971)

### PR DESCRIPTION
**Pull request by cani1see**
fix defaultOptions not respect on Android

### CODE REVIEW

**Comment by guyca** [comment]
Hey @cani1see 👋 
Which option exactly doesn't respect default options? Can you please prodive a reproduction?

**Comment by cani1see** [comment]
@guyca statusBar.drawBehind  you hava commented in the ori issue ,
 reproduction  in https://github.com/cani1see/react-native-navigation/tree/reproduction.  
options tab try last two buttons.

**Comment by danilobuerger** [comment]
Ref #5971

**Comment by guyca** [comment]
@cani1see Thanks for providing a reproduction! I'm closing the PR and will submit a PR of my own today 👍

**Comment by danilobuerger** [comment]
Ref #6683

**Pull request closed without merging**
