### PR TITLE
NavigationActivity implements PermissionAwareActivity

### PR DESCRIPTION
**Pull request by chaitanya0bhagvan**
To target android API 23 and above, an activity must perform permission handling. React native already provides PermissionAwareActivity interface. NavigationActivity must implement PermissionAwareActivity to handle permissions.

### CODE REVIEW

**Comment by chaitanya0bhagvan** [comment]
@guyca Any update on when this will be merged.

**Comment by guyca** [comment]
Hey @chaitanya0bhagvan 
Thanks for the PR. I wrote some comments regarding styling, can you address them?

**Comment by chaitanya0bhagvan** [comment]
Hey @guyca yes I can absolutely make those changes, but I don't see any comments.

**Comment by chaitanya0bhagvan** [comment]
@guyca I have made some styling changes to be consistent with the rest of the code. Please take a look and tell me know if you need something else to be changed to merge this PR.

**Comment by chaitanya0bhagvan** [comment]
@guyca I guess I am not too familiar with github. I have removed Hungarian notations from the file.

**Comment by shafy** [comment]
Cool guys! When will this be in experimental?

**Comment by florianbepunkt** [comment]
I can't get this to work. I updated to latest version just now by using
npm install react-native-navigation@next --save

before I start my tabBasesApp I check for permissions like this

```
PermissionsAndroid
  .checkPermission(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
  .then((resp) => {
    console.log(resp);
    if(resp === false) {
      PermissionsAndroid
        .requestPermission(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
    }
  });

Navigation.startTabBasedApp({
…omitted for brevity…
});

```

but this gives me an error:

`"Tried to use permissions API while not attached to an Activity"`

Can you guys help?

**Comment by guyca** [comment]
@florianbepunkt It won't work before the call to `startTabBasedApp` since `NavigationActivity`, which implement `PermissionAwareActivity` isn't running. You should call `checkPermission` api as close as possible to the moment you actually require a permission, and only after your app is actually running. Hope this helps.

**Pull request merged**
