### PR TITLE
Support swipeable component on iOS

### LINKED ISSUE #3575: [v2] cannot use a swipeable element on iOS when using side drawer
### Issue Description

I am using a swipable list view (from native-base) in a tab view layout that has a **left** side drawer. I want to swipe left from the **right**, but it does not work on iOS. it works on android. on iOS, I can drag it only for about 10 pixels.

### Steps to Reproduce / Code Snippets / Screenshots

screen shot 2018-07-17 at 4 05 08 pm
screen shot 2018-07-17 at 4 06 56 pm

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.2.412
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

### PR DESCRIPTION
**Pull request by ujwal-setlur**
Hi,

This resolves #3575, where I could not use a swipeable component like Swipeable ListView on iOS when I was using a side drawer. The openDrawer gesture was taking over from the swiping action. This change disables the drawer swipe open gesture from the center view. I think this is acceptable since drawers can still be dragged open from the edges, and this seems to be standard behavior on iOS anyway.

If there is a better way to do this, please let me know. Thanks!

### CODE REVIEW

**Comment by ujwal-setlur** [comment]
I will look at the failing test

**Comment by ujwal-setlur** [comment]
This test is failing because there seems to be an issue in detox framework to have swipe start with an element at the left edge. The swipe action does not start at the element. Here is a related issue filed against detox:

https://github.com/wix/detox/issues/566

Here is the attempted test which should have worked:

```
  test(':ios: switch to tabs with side menus', async () => {
    await elementById(testIDs.TAB_BASED_APP_SIDE_BUTTON).tap();
    await elementById(testIDs.LEFT_EDGE_TEXT).swipe('right');
    await expect(elementById(testIDs.HIDE_LEFT_SIDE_MENU_BUTTON)).toBeVisible();
  });
```

The element with ```testID=LEFT_EDGE_TEXT``` was placed at the left edge of the screen.

**Comment by ujwal-setlur** [comment]
Not a single comment...

**Comment by pkyeck** [comment]
why is nobody looking at these PRs?

**Comment by ujwal-setlur** [comment]
Frankly, lack of developer response caused me me to move away from this project. I understand they are busy, but...

**Comment by ItsNoHax** [comment]
@ujwal-setlur @pkyeck The devs are currently looking into this and they are implementing it the correct way. I expect this issue to be fixed by the next stable release, 2.1.4.

Refer to: https://github.com/wix/react-native-navigation/commit/0a4bf2ade3b8b98041c8a6057d26a254e193d84d
and https://github.com/wix/react-native-navigation/commit/6b5fe800910214873b1ceafbccefea9ccfac7dda

**Comment by pkyeck** [comment]
@ItsNoHax thanks for the update. Next time the devs should add some ref or whatever, so that people that want to contribute get some feedback on the status.

**Comment by ItsNoHax** [comment]
Going to close this PR as it is no longer relevant. For the record, if you really need a fast reply you are welcome to join the Discord and ask your questions there.

**Pull request closed without merging**
