### PR TITLE
Fix memory issues

### PR DESCRIPTION
**Pull request by bitcrumb**
* Fix retain cycles
* Explicitly destroy previous rootViewController views

### CODE REVIEW

**Comment by bitcrumb** [comment]
Sorry, opened PR against wrong repository 😓

**Comment by guyca** [comment]
No worries @bitcrumb! Any plans on PRing those changes to upstream? I see you guys have addressed the fade animation issue when calling setRoot! This bug was reported several times lately here in the issue tracker.

**Comment by bitcrumb** [comment]
@guyca I wasn't sure if you would be interested :)

I'll look into it when I find some spare time :)

**Comment by guyca** [comment]
Yeah that would be awesome! I actually spoke with @jarnove a while ago about addressing the setRoot animation issue but we never got around to it :(
Lets coordinate this on [Discord](https://discord.gg/DhkZjq2)!

**Pull request closed without merging**
