### PR TITLE
[v2] Fixes issues#1397

### PR DESCRIPTION
**Pull request by joonhocho**
https://github.com/wix/react-native-navigation/issues/1397

Tested it and it works well with or without remote debugging enabled.

### CODE REVIEW

**Comment by joonhocho** [comment]
Note that it does not fix appLoaded event being raised multiple times due to many js bundles. It fixes app hanging due to not getting the event.

**Comment by DanielZlotin** [comment]
Thanks for the PR.
I want to reproduce it somehow with tests before merging this,
I think this reproduces on latest RN, I'll upgrade soon and check

**Comment by joonhocho** [comment]
@DanielZlotin FYI I am using RN 0.47.2.

**Comment by AdamLiechty** [comment]
This reproduces on RN 0.50.3 as well.

**Comment by shuse2** [comment]
For RN 0.50.3, I checked both with and without debugger, and this fix works!

**Comment by steffenmllr** [comment]
Fix works for:

```
    "react-native": "0.50.3",
    "react-native-navigation": "^2.0.2031",
```

**Comment by anonrig** [comment]
Such a major bug in v2, didn't get fixed. Any body working on this atm?

**Comment by brunolemos** [comment]
@anonrig while it is not merged, you can apply the fix using [patch-package](https://github.com/ds300/patch-package).

Follow the instructions in the patch-package README and create a file named `react-native-navigation+2.0.2042.patch` (change version accordingly) with this content:

```
patch-package
--- a/node_modules/react-native-navigation/lib/ios/RNNEventEmitter.m
+++ b/node_modules/react-native-navigation/lib/ios/RNNEventEmitter.m
@@ -1,6 +1,9 @@
 #import "RNNEventEmitter.h"
 
-@implementation RNNEventEmitter
+@implementation RNNEventEmitter {
+  NSInteger _appLaunchedListenerCount;
+  BOOL _appLaunchedEventDeferred;
+}
 
 RCT_EXPORT_MODULE();
 
@@ -15,9 +18,14 @@ static NSString* const onNavigationButtonPressed	= @"RNN.navigationButtonPressed
 
 # pragma mark public
 
--(void)sendOnAppLaunched {
+-(void)sendOnAppLaunched {
 	[self send:onAppLaunched body:nil];
-}
+	if (_appLaunchedListenerCount > 0) {
+		[self send:onAppLaunched body:nil];
+	} else {
+		_appLaunchedEventDeferred = TRUE;
+	}
+ }
 
 -(void)sendContainerDidAppear:(NSString *)containerId {
 	[self send:containerDidAppear body:containerId];
@@ -31,10 +39,24 @@ static NSString* const onNavigationButtonPressed	= @"RNN.navigationButtonPressed
 	[self send:onNavigationButtonPressed body:@{@"containerId":containerId , @"buttonId": buttonId }];
 }
 
+- (void)addListener:(NSString *)eventName {
+	[super addListener:eventName];
+	if ([eventName isEqualToString:onAppLaunched]) {
+		_appLaunchedListenerCount++;
+		if (_appLaunchedEventDeferred) {
+			_appLaunchedEventDeferred = FALSE;
+			[self sendOnAppLaunched];
+		}
+	}
+}
+
 # pragma mark private
 
 -(void)send:(NSString *)eventName body:(id)body {
-	[self sendEventWithName:eventName body:body];
+	// TODO This is a quick and dirty fix to issues/#1514.
+	if ([self bridge] != nil) {
+		[self sendEventWithName:eventName body:body];
+	}
 }
 
 @end
```

After every `npm install` or `yarn` it will apply this fix to the node_modules/react-native-navigation project.

**Comment by pentarex** [comment]
this patch does not work for me.
cannot debug and also receiving 
```swift
Sending `RNN.appLaunched` with no listeners registered. 
```
```bash
react-native-navigation: 2.0.2070
react-native: 0.51.0
node: 9.3.0
npm: 5.6.0
```

**Pull request merged**
