### PR TITLE
Added steps to fix Xcode 10 'Multiple commands produce…' build issue

### LINKED ISSUE #3608: [V2] Build error in Xcode 10 "Multiple commands produce..."
### Issue Description

After following the [installation instructions](https://wix.github.io/react-native-navigation/v2/#/docs/Installing) multiple times and clearing caches in between I still get build errors in Xcode 10:

### Steps to Reproduce / Code Snippets / Screenshots

image

---
### Environment
* React Native Navigation version: 2.0.2425
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 
* No other dependencies except `react-native-navigation` installed

### PR DESCRIPTION
**Pull request by cheloveq**
Added a few lines to the Installation docs explaining how to solve build error "Multiple commands produce…" in Xcode 10. 
Fixes #3608

### CODE REVIEW

**Comment by henrikra** [comment]
Maybe also add note that this happens on XCode 10?

**Comment by Fabian-Fynn** [comment]
`Copy only when installing` is not a fix.
Each time `yarn` is executed the checkbox has to be ticked again.

Isn't there a way to set this permanently?

**Comment by cheloveq** [comment]
@henrikra I did mention that in the first sentence. Anywhere else I should put it?
@Fabian-Fynn That is true and I added that as a note following the steps. Personally I am not aware if it's possible to set it permanently, this is a workaround.

**Comment by rajivshah3** [comment]
#4321 effectively does this, but permanently. The `Copy Files` phase is creating duplicate files

**Comment by yogevbd** [comment]
Fixed here: #4220, no need to go through does steps anymore

**Comment by rajivshah3** [comment]
@yogevbd you beat me to it 😄

**Pull request closed without merging**
