### PR TITLE
[v2] TabBarItem support for iOS

### PR DESCRIPTION
**Pull request by joonhocho**
I am adding customizing TabBarItem for iOS.
Most of codes are ported from v1.

### CODE REVIEW

**Comment by DanielZlotin** [comment]
Thank you for the PR, @bogobogo please review, seems like some things are duplicated with our current codebase

**Comment by joonhocho** [comment]
Also added support for default selected index. It's as easy as putting 'selected: true' to your tab definition:
```javascript
{
selected: true,
container: {...},
tabItem: {...}
}
```

**Comment by larryranches** [comment]
@joonhocho Does this support changing background colors for an individual tab?

**Comment by yogevbd** [comment]
fixed in #2571

**Pull request closed without merging**
