### PR TITLE
Fix/#6773 custom title component

### PR DESCRIPTION
**Pull request by simonmitchell**
Fixes issue #6773 where calling `setDefaultOptions` (And possibly other methods) with a custom component in the title of the navigation (And probably in other places too) would cause an error due to the assumption that any key in the options dictionary with value `component` would itself be a valid object containing a `name` key itself.

### CODE REVIEW

**Review by danilobuerger — CHANGES_REQUESTED** [review]
Please get rid of the inner `if` and move the condition to the outer `if`.

**Comment by danilobuerger** [comment]
Hi @simonmitchell. I don't really understand what this is trying to fix. When would `component` not be an object and contain a `name`? As you can see from the typings (left out unrelated fields):
```
export interface OptionsTopBarTitle {
  component?: {
    name: string;
  };
}
```
the `name` is required if the `component` is specified.

**Comment by simonmitchell** [comment]
Hi @danilobuerger, the problem is that the function call is recursive, see the end of the `processObject` function:

```
const processedValue = objectToProcess[key];
if (!isEqual(key, 'passProps') && (isObject(processedValue) || isArray(processedValue))) {
   this.processObject(processedValue, parentOptions, onProcess, commandName, objectPath);
}
```

In our case, this leads to `processComponent` being called with a value that is a react component due to the options object we are passing in:

```
component: {
  name: "navigation.title",
  alignment: "center",
  component: require("components/common/navigation/title")
}
```

**Comment by simonmitchell** [comment]
See issue, can be ignored, this was a coding error from a previous dev on our project that I assumed was an issue with this repo. My apologies!

**Pull request closed without merging**
