### PR TITLE
[V2][IOS] Resolve 'push'-command with next componentId for ios

### PR DESCRIPTION
**Pull request by Hesowcharov**
Behavior of `Navigation.push(someComponentId, layout)` between android and ios is different.
In android promise resolves with next componentId (id of component that was pushed), but on ios - componentId on which we pushed.
Android: [https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L145](url)
Motivation of this PR - keep api behavior more consistent.

### CODE REVIEW

**Comment by henrikra** [comment]
Good catch!

**Comment by henrikra** [comment]
Can you also fix the return type of `push` to the TypeScript file? https://github.com/wix/react-native-navigation/blob/v2/lib/src/Navigation.ts#L114

**Comment by Hesowcharov** [comment]
Sorry for long inactivity. 
Updated PR according to new interfaces and fix failed tests (ios, type-error). Also, in current version 'setStackRoot' promise resolves with last child componentId.

**Comment by hannojg** [comment]
Hey! This really needs to be merged!

**Comment by hannojg** [comment]
I created a new, conflict-free, PR: https://github.com/wix/react-native-navigation/pull/6445

**Comment by danilobuerger** [comment]
This was addressed in #6422 and has been released in v7.

**Pull request closed without merging**
