### PR TITLE
Fix crash on ios when setting topbar left buttons with custom component

### PR DESCRIPTION
**Pull request by MarianPalkus**
Possible fix for crash on ios when setting topbar left buttons with custom component.

Fixes issue #5180.

### CODE REVIEW

**Comment by hemith** [comment]
Setting topbar left buttons with custom component on android is not working too. check it out please.

**Comment by MarianPalkus** [comment]
@hemith i could not reproduce a crash for the same situation on android (emulator).

**Comment by hemith** [comment]
@MarianPalkus OK I got it. 
I have a problem setting topbar left buttons with custom component on android.
Right buttons are appear. but left buttons are not appear.  (no crash)
I didn't check it out on iOS.
Anyway i think my problem is not much related with this pull request.
thank you! :-)

**Comment by MarianPalkus** [comment]
@hemith Ok, thanks for clarification :-)

**Pull request merged**
