### PR TITLE
Fix updateProps creating new props object

### PR DESCRIPTION
**Pull request by jinshin1013**
This PR closes https://github.com/wix/react-native-navigation/issues/6262.

### CODE REVIEW

**Comment by jfrolich** [comment]
Be very carefull with this. I am pretty sure this cloneDeep is there for a reason (I did touch this code some time ago but I don't know the specifics anymore).

**Comment by jfrolich** [comment]
Ah yes some operations are mutable such as here: https://github.com/wix/react-native-navigation/blob/9ef61a9a1357312208463ef149a7951931043d1e/lib/src/commands/OptionsProcessor.ts. So you need to clone the tree first so you can mutate the new tree.

**Comment by jfrolich** [comment]
Actually I think you can remove the clone deep specifically for the `updateProps` function, as there doesn't seem to be mutation involved.

**Comment by jinshin1013** [comment]
@jfrolich Hmm yeah, looks like some of the other commands are accessing the cloned object. Yeah I'll change it to only use `clone` for `updateProps`.

**Comment by jinshin1013** [comment]
Hmmm, I'm not sure if it is worth changing the current behaviour as there are other ways for the consumer to be checking the equality of the objects.

**Comment by jfrolich** [comment]
I think for updateProps, not cloning and just passing the object is probably better. It will allow creating a memoized component.

**Comment by guyca** [comment]
@jinshin1013 I tend to agree with @jfrolich on this one. Cloning props here is probably my mistake. We clone *options* passed to other commands but in this case, cloning is actually a mistake as it prevents a basic optimisation with the `===` equality check.

What do you say we reopen the PR and remove all clone/cloneDeep from the `updateProps` command?

**Pull request merged**
