### PR TITLE
Fix flash issue, Added ability to set secondary badge

### PR DESCRIPTION
**Pull request by shahen94**
Closes out #358 #828 #757 

I've debounce the push method to make sure that the react views will be rendered until they will be visible

Also added ability to add secondary badge for every tab (iOS only)

### CODE REVIEW

**Comment by juancaacuna** [comment]
We need this! Thanks!!

**Comment by guyca** [comment]
@shahen94 @gevorg94 As discussed on discord i'm closing the pr.
The white flash on iOS should be addressed but adding a timeout is a bit problematic, support for custom BottomTabs will probably be included in 2.x. Thanks a lot guys 👍

**Comment by juancaacuna** [comment]
@guyca Yes, the white flash on iOS is urgent. Thank you!

**Comment by Mark2xv** [comment]
Excuse me for the necro.
Might I ask why this was closed? Not everyone is involved on the discord channel. At the very least, could you state the reasons why this was rejected?

The white flashes are quite an issue as far as I'm concerned. And if I'm completely honest, a  workaround with a solid background image or color isn't really a solution either. Why not just wait until there has been a render on the screen? 

This issue has been closed for 9 months now stating the solution would come in v2. v2 is not done yet, as far as I'm aware. Thus you have rejected a potential solution to a big issue while not coming up with something better for three quarters of a year. Why?

Excuse me if this sounds hostile, that is not my intent. I'm just trying to figure out *why*.

**Comment by guptarohit** [comment]
This is still a issue.

**Comment by guyca** [comment]
Hey @Mark2xv 
To avoid the while flash, this pr introduced a hardcoded delay when pushing screen. While this will effectively eliminate the white flash, it's not an acceptable solution.

This issue is resolved for both platforms on v2. The reason we're not resolving this in v1 is simply because we don't want to invest any resources in v1 so we can transition as soon as possible to v2.

If someone would like to PR this for v1, the propper way is to use [RCTContentDidAppearNotification](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/Base/RCTRootView.m#L35)

**Pull request closed without merging**
