### PR TITLE
Fixed an issue with the React navigation animations

### PR DESCRIPTION
**Pull request by voidstarfire**
https://github.com/wix/react-native-navigation/issues/1861

### CODE REVIEW

**Comment by guyca** [comment]
Hey @voidstarfire,
The alpha animation was actually intentionally removed from `slide-horizontal` animation. Personally, I think the animation looks better with out the alpha. Also I've noticed that Samsung has changed the default activity animation on their devices to slide animation, which doesn't have an alpha component. Of course the iOS slide animation also doesn't have alpha.

I think we should keep the `slide-horizontal` animations as is, with out alpha. If you'd like, you're welcome to add a new animation type with alpha. wdyt?

**Comment by voidstarfire** [comment]
Maybe there should be an option? (Like a boolean flag for both imcomming and outgoing)

Personally I think the alpha looks much better because the slide animation sometimes lags and lowers the quality of the app's appearance.

Also the slight fade gives the impression that the app is silky smooth and going backwards feels like a much nicer process. At the moment it feels very iOS'y.

This was originally raised as bug by my QA team hehe. (Why are screens not fading).
According to material design sliding in and direction where-by a screen is destroyed should be accompanied by a fade at least.

**Comment by guyca** [comment]
Adding a new type `slide-horizontal-fade` sounds like a good idea 👍

**Comment by voidstarfire** [comment]
Great
I'll get into it next week :-)
When was this removed? (I'd like to reference old source code)

**Comment by guyca** [comment]
89eb30a54290950426b94ebe0b9fc5c7560cb259

**Comment by voidstarfire** [comment]
FYI I will begin work on this tomorrow, been on vacation (Just letting you know so you don't close)

**Comment by voidstarfire** [comment]
I don't have time do this now, (currently working 60 hour weeks) can somebody else take it over thanks?

**Comment by guyca** [comment]
Closing the pr as custom animations are supported in v2

**Pull request closed without merging**
