### PR TITLE
Improve documentation of back navigation

### PR DESCRIPTION
**Pull request by guyca**

### CODE REVIEW

**Review by mrousavy — APPROVED** [review]
I like it 🤗

**Comment by guyca** [comment]
Thanks for reviewing @mrousavy 🙇 
I'm still not sure why the link is broken 😭

**Comment by mrousavy** [comment]
@guyca  try using absolute links. start with `/`

**Comment by guyca** [comment]
> @guyca try using absolute links. start with `/`

I'll give it a shot!

**Review by yogevbd — APPROVED** [review]

**Pull request merged**
