### PR TITLE
Fixed compatibility with React Native 0.40.0

### PR DESCRIPTION
**Pull request by dcgoss**
Fixed imports of iOS headers mentioned in https://github.com/facebook/react-native/releases/tag/v0.40.0.

Another issue is that the RCTReloadNotification constant was removed in https://github.com/facebook/react-native/commit/cd2b384ec42843c1f68fcaef344ffd2f17dd0a5d. I'm not entirely sure what to replace it with, but for now I just replaced it with RCTJavaScriptWillStartLoadingNotification just so that everything compiles and runs. Hoping someone with more experience can look at that.

### CODE REVIEW

**Comment by DanielZlotin** [comment]
Amazing, thank you! I can't accept this yet as this is a breaking change, will accept as soon as we move to 0.40.0

**Comment by jaggerwang** [comment]
When will this pull request be merged?

**Comment by simonmitchell** [comment]
@guyca we have a fix for the RCTReloadNotification being removed on our fork if you'd like me to PR it?

**Comment by guyca** [comment]
@simonmitchell That would be great! thanks.

**Comment by simonmitchell** [comment]
@guyca submitted a PR here for this: https://github.com/wix/react-native-navigation/pull/733, however someone may have done a better job than us in replacing `RCTReloadNotification` here: https://github.com/wix/react-native-navigation/pull/723 :)

**Comment by guyca** [comment]
Support for RN 0.41.2 was added in 503eef5 cc94e02 fc357ba

**Pull request closed without merging**
