### PR TITLE
Fix rn 0.50 repeated calls to onMeasure.

### PR DESCRIPTION
**Pull request by chaitanya0bhagvan**
RN 0.50 introduced a new feature to dynamically measure ReactRootView. Since RNN uses RelativeLayout for Screen and BottomTabsLayout child views added to the layout may have additional rules. When the child views are measured they are measured with respect to the LayoutParams set during Screen creation and the Parent MeasureSpec. In RNN, ContentView extends ReactRootView and it calls onMeasure using the widthMeasureSpec and heightMeasureSpec passed to it. If these measureSpecs are EXACTLY then ReactRootView will measure itself to fit the exact size requested by the parent. 

If ContentView was added with LayoutParams.MATCH_PARENT for height and/or width with additional rules eg. BELOW or ABOVE the effective height of this View may not be compatible with MATCH_PARENT. RelativeLayout does two passes over its children, in the first pass each child is measured as per their LayoutParams, in the second pass LayoutParam rules are applied and each child is measured. The problem occurs here, if ReactRootView was asked to measure itself with MeasureSpec.EXACTLY but the measuredHeight was less than expected it will trigger a requestLayout() causing the entire layout to be remeasured. 

The fix is to call super.onMeasure() in ContentView with MeasureSpec.AT_MOST.

### CODE REVIEW

**Comment by enahum** [comment]
is there anything else needed for this PR to get merged?

**Comment by bitcrumb** [comment]
Anything that is holding back this PR? If not, would like to see this merged as soon as possible :)
Thanks!

**Comment by CherishIt** [comment]
Also waiting for this PR being merged to carry on with my work, thanks.

**Comment by fforres** [comment]
Friendly Ping @guyca and/or @DanielZlotin  ? :)

**Comment by ChristianAyala** [comment]
I can also confirm that this fixes the flickering issue in our app. Would love to see this merged in soon!

**Comment by koansang** [comment]
When do you merge this PR? @guyca

**Comment by ReggaePanda** [comment]
it works! thanks 🥇

**Comment by Flavien** [comment]
Is that on NPM yet?

**Comment by ReggaePanda** [comment]
@Flavien yes, I use yarn and with `yarn upgrade-interactive` I updated my project and `yarn start --reset-cache` it fixed this issue.

**Comment by jasonmerino** [comment]
Looks like this fix was released with version `1.1.307`. 🙌🏼

**Comment by ariona** [comment]
This fix the flickering view issue on my app :clinking_glasses:

**Comment by skovhus** [comment]
@chaitanya0bhagvan is this backwards compatible? So we can use this with react-native < 0.50?

I really miss a change log here or at least which versions that depends on which react-native versions.

Related #1551

**Comment by chaitanya0bhagvan** [comment]
@skovhus This is backward compatible change. As of now the docs and examples have not been updated to reflect RN 0.50 change where `index.android.js` and `index.ios.js` have been replaced with `index.js`. Let me know if you need any help with the RN upgrade.

**Pull request merged**
