### PR TITLE
PlatformColor Support

### PR DESCRIPTION
**Pull request by swabbass**
Following the discussion here: #6618.

## Android
- Colours are parsed natively.
- Creating custom colour when a PlatformColor is passed to native.
- Both light/dark values have the same res attribute resolved when `get` is called.

## IOS
- Added a custom colour.
- Changed storyboard splash screen.
- Using `labelColor` as a test.

CC: @yogevbd 
closes: #6618

### CODE REVIEW

**Comment by swabbass** [comment]
@yogevbd I added a custom colour in `Images.xcassets` and did not work for me referring to it from `PlatformColor(rnnTextColor)`, I'm sure I'm missing something, using `labelColor` works just fine, it needs your final touches on iOS and we are ready to go.

**Review by yogevbd — APPROVED** [review]

**Comment by habovh** [comment]
@swabbass it seems the alleged `labelColor` test is missing from this PR.

I'm encountering the following error on 7.20.0 (iOS-only snippet):

```js
Navigation.setDefaultOptions({
  bottomTabs: {
    backgroundColor: PlatformColor('systemBackground'),
  },
  bottomTab: {
    textColor: PlatformColor('label'),
    iconColor: PlatformColor('label'),
  },
})
```

```
JSON value '{
    dynamic =     {
    };
}' of type NSMutableDictionary cannot be converted to a UIColor. Expected an iOS dynamic appearance aware color.

+[RCTConvert UIColor:]
    RCTConvert.m:913
+[ColorParser parse:key:]
-[RNNBottomTabsOptions initWithDict:]
-[RNNNavigationOptions initWithDict:]
-[RNNCommandsHandler setDefaultOptions:completion:]
__55-[RNNBridgeModule setDefaultOptions:resolver:rejecter:]_block_invoke
RCTExecuteOnMainQueue
-[RNNBridgeModule setDefaultOptions:resolver:rejecter:]
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0
```

**Comment by svbutko** [comment]
> @swabbass it seems the alleged `labelColor` test is missing from this PR.
> 
> I'm encountering the following error on 7.20.0 (iOS-only snippet):
> 
> ```js
> Navigation.setDefaultOptions({
>   bottomTabs: {
>     backgroundColor: PlatformColor('systemBackground'),
>   },
>   bottomTab: {
>     textColor: PlatformColor('label'),
>     iconColor: PlatformColor('label'),
>   },
> })
> ```
> 
>  ```
> JSON value '{
>     dynamic =     {
>     };
> }' of type NSMutableDictionary cannot be converted to a UIColor. Expected an iOS dynamic appearance aware color.
> 
> +[RCTConvert UIColor:]
>     RCTConvert.m:913
> +[ColorParser parse:key:]
> -[RNNBottomTabsOptions initWithDict:]
> -[RNNNavigationOptions initWithDict:]
> -[RNNCommandsHandler setDefaultOptions:completion:]
> __55-[RNNBridgeModule setDefaultOptions:resolver:rejecter:]_block_invoke
> RCTExecuteOnMainQueue
> -[RNNBridgeModule setDefaultOptions:resolver:rejecter:]
> __invoking___
> -[NSInvocation invoke]
> -[NSInvocation invokeWithTarget:]
> -[RCTModuleMethod invokeWithBridge:module:arguments:]
> facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
> facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
> invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_main_queue_callback_4CF
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> __CFRunLoopRun
> CFRunLoopRunSpecific
> GSEventRunModal
> -[UIApplication _run]
> UIApplicationMain
> main
> start
> 0x0
> ```

Same thing but for me it briefly appears and disappears and colors are assigned properly

**Comment by habovh** [comment]
@svbutko I also have the error appearing and disappearing if only assign the backgroundColor on `bottomTabs`. With both `bottomTabs` background color and `bottomTab` *colors, the error shows up every time and stays.

**Comment by svbutko** [comment]
Found it, it happens with every navigation component on iOS

Color comes to `OptionsProcessor` as `{"dark": undefined, "light": undefined, "semantic": ["systemBackground"]}` on init and as `{"semantic": ["systemBackground"]}` after merges

And this value goes through `DynamicColorIOS(options[key])` which produces `{"dynamic": {"dark": undefined, "highContrastDark": undefined, "highContrastLight": undefined, "light": undefined}}`

**Comment by swabbass** [comment]
> "

CC: @yogevbd

**Pull request merged**
