### PR TITLE
Added TitleState showWhenActiveForce option for bottomTabs

### LINKED ISSUE #5800: titleDisplayMode doesn't work with three bottom tabs
### Issue Description

titleDisplayMode: 'showWhenActive' doesn't work with three or less bottom tabs. It always show the titles.

With four or more tabs, it works ok.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setRoot({
      root: {
        bottomTabs: {
          ...
          children: [
            {
              stack: {
                children: [
                  {
                    component: {
                     ...
                      options: {
                        bottomTab: {
                          text: translations.messages.toUpperCase(),
                          textColor: '#ffffff',
                          selectedTextColor: '#ffffff',
                          selectedIconColor: '#ffffff',
                          fontFamily: 'Roboto',
                          icon: tabbar.messages
                        }
                      }
                    }
                  }
                ]
              }
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      ...
                      options: {
                        ...
                        bottomTab: {
                          text: translations.games,
                          textColor: '#ffffff',
                          selectedTextColor: '#ffffff',
                          selectedIconColor: '#ffffff',
                          fontFamily: 'Roboto',
                          icon: tabbar.games
                        }
                      }
                    }
                  }
                ]
              }
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      ...
                      options: {
                       ...
                        bottomTab: {
                          text: translations.profile,
                          textColor: '#ffffff',
                          selectedTextColor: '#ffffff',
                          selectedIconColor: '#ffffff',
                          fontFamily: 'Roboto',
                          icon: tabbar.account
                        }
                      }
                    }
                  }
                ]
              }
            }
          ],
          options: {
            bottomTabs: {
              currentTabIndex: 2,
              visible: true,
              backgroundColor: COLOR.MaterialPrimary,
              drawBehind: false,
              animate: false,
              titleDisplayMode: 'showWhenActive',
            }
          }
        }
      }
    })
```

---
### Environment
* React Native Navigation version: 4.0.8
* React Native version: 0.60.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator and Device (OnePlus 5, Android 9 Pie). Debug and release.

### PR DESCRIPTION
**Pull request by BenJeau**
### Android Bottom Navigation Tabs

_**Related Issue**_
Closes #5800

_**Description**_
When playing around with [AHBottomNavigation](https://github.com/aurelhubert/ahbottomnavigation) demo app, in order to only show to title of the active bottom tab when there's three tabs, the `TitleState` needs to be set to `SHOW_WHEN_ACTIVE_FORCE`. 

Adding these changes allow for this behavior in RNN, but when I'm clicking on a tab, the app dies. I only added this change to the playground app, to the bottomTabs root in `app.js`:

```
options: {
  bottomTabs: {
    titleDisplayMode: 'showWhenActiveForce'
  }
}
```

Would anyone have a pointer on how to fix this or how to figure out what's wrong?

### CODE REVIEW

**Comment by guyca** [comment]
@BenJeau, I just published version version 3.0.9 - can you please try it and see if it fixes the crash when changing tabs?

**Comment by BenJeau** [comment]
Just rebased with master (ignore the multiple force-pushed, it's weird rebased a fork), but the app still crashed when adding this option `titleDisplayMode: 'showWhenActiveForce'` to bottomTabs and clicking a tab, but if you look, it correctly displays at least

screenshot

**Comment by guyca** [comment]
@BenJeau Have you tried using version 3.0.9 of https://github.com/wix-playground/ahbottomnavigation ? You can change it [here](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/build.gradle#L100) and recompile

**Comment by BenJeau** [comment]
Yep it works now and doesn't crash! Will push a commit soon

**Pull request merged**
