### PR TITLE
Update react-native to 0.65.1

### PR DESCRIPTION
**Pull request by svbutko**
I updated react-native to 0.65.1 and tested on both Android and iOS playground apps but in debug only, also updated several dependencies, would be awesome if you could take a look at it more carefully in terms of tests and release versions

### CODE REVIEW

**Comment by svbutko** [comment]
image

**Comment by swabbass** [comment]
Looks cool dude, we already have https://github.com/wix/react-native-navigation/pull/7034, make sure to merge your changes in that PR. and this can be closed.

**Comment by svbutko** [comment]
Oh, didn't see it existed already, I'll do it then

**Comment by swabbass** [comment]
Also, we want to stick to the RN kotlin version, to avoid inconsistencies, I removed legacy stuff, so you might need to have a quick pass over the changes

**Comment by svbutko** [comment]
Changed the merge remote to RN64 and resolved conflicts

**Comment by svbutko** [comment]
I bumped Kotlin version a bit because it fixes some Kotlin issues, I think it won't do any changes to RN

**Comment by svbutko** [comment]
@swabbass can I merge my changes into RN64 or it would be better to check it first for you?

**Pull request merged**
