### PR TITLE
iOS - add disabledBackGesture

### PR DESCRIPTION
**Pull request by gran33**
This new style will NOT pass between push screens.

### CODE REVIEW

**Comment by grundmanise** [comment]
So we possibly can use this new param to disable back gesture on all root screens and prevent https://github.com/wix/react-native-navigation/issues/428 ?

**Comment by gran33** [comment]
As far as I see, the real problem in #428 is the fact that the cell isn't push any more and the swipe is just weird thing that happened. So, `disabledBackGesture` will just prevent the swipe gesture, no more then this. If it solves any other bugs, use it.

**Comment by grundmanise** [comment]
This in not the issue with the cell, it happens when you swipe from left to right on the root screen. https://github.com/wix/react-native-navigation/issues/645 <- same issue. Thanks for the commit, it is a useful feature.

**Comment by grundmanise** [comment]
@gran33 only thing is that we should document this new param.

**Comment by gran33** [comment]
@grundmanise thanks for the reminder.
https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator#style-object-format

**Comment by kl** [comment]
I don't think you should edit the wiki until the patch is merged. Now the ```disabledBackGesture``` property is documented but it has no effect, which is very confusing. Any chance of getting this merged into master?

**Comment by nbonamy** [comment]
@kl agreed. was struggling with it until I found your comment!

**Pull request merged**
