### PR TITLE
Official redux support

### PR DESCRIPTION
**Pull request by DanielZlotin**
The people have spoken.

### CODE REVIEW

**Comment by rfdc** [comment]
I have tried few option from #1642 and did not work. 
What is the solution? Is there an example showing the whole process? 
Thanks

**Comment by tiempham** [comment]
@DanielZlotin  Can you show an example? I don't understand function parameters. Thanks

**Comment by drorbiran** [comment]
Hi, Here is an example of a super simple project with Redux
https://github.com/drorbiran/react-native-simple-blog/blob/redux/src/screens.js

**Comment by DanielZlotin** [comment]
Updated with example

**Comment by spacesuitdiver** [comment]
@DanielZlotin sorry if this is contained in some other discussion. Was there a technical reason we chose to explicitly provide a method to register components with redux instead of just having everyone figure this out with HOCs (or some other solution)?

**Comment by mammad2c** [comment]
componentDidAppear not working in v2.0.2472
Is there any other way to connect redux ?

**Comment by DanielZlotin** [comment]
Nothing wrong with doing your own HOCs. Just that lots of people had problems implementing it, so we added this as a "quality of life" feature.

**Comment by spencewine** [comment]
@DanielZlotin I'm getting this error: `Cannot read property 'componentId` of null when using `registerComponentWithRedux`. Any idea why this would happen?
screen shot 2018-08-17 at 11 43 06 am

**Comment by ywongweb** [comment]
@spencewine Did you managed to find a solution?

**Comment by wbercx** [comment]
@DanielZlotin Just wanted to provide some feedback on this. I recently overheard someone suggest the latest version of RNN only supports Redux.

The implementation isn't limited to Redux and, for example, works fine with `mobx-react` as well. The current naming does not suggest that though.

I think it may make more sense to have this be called `registerComponentWithProvider`. It seems that captures what this essentially does - it let's you use *a* Provider.

**Comment by DanielZlotin** [comment]
Ah I knew this would happen :facepalm: that's why I was reluctant to add this in the first place.
Thanks for the feedback.

**Comment by wbercx** [comment]
Nah, it's a fantastic addition, it's just the naming that's is a bit more specific than it needs to be :grin:

**Comment by DanielZlotin** [comment]
The store argument is kinda redux specific though.. Please open a separate issue with a better api suggestion and we'll deprecate the current api if needed.
Thanks

**Comment by alzalabany** [comment]
Does this work with new context api providers ?

**Comment by barjas** [comment]
any step by step plz ?

**Pull request merged**
