### PR TITLE
[iOS] Support Fabric

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary
This is part of #5080. It is the required changes to the iOS side of RNN to support the Fabric architecture. I am testing this in my own application.

Limitations:
1. Currently, it replaces the paper implementation. 
2. Currently only supports cocoapods, no plan for RN to support non-cocoapods version.
3. iOS enabled only.

### CODE REVIEW

**Comment by SudoPlz** [comment]
What benefits do we get from enabling fabric on rnn?

**Comment by ericlewis** [comment]
@SudoPlz lower memory usage, faster app with sync drawing.

**Comment by SudoPlz** [comment]
@ericlewis can you please point me to where you found documentation for this? I'd love to get my hands dirty w/ fabric, and I have no idea what to enable in the Xcode project.

**Comment by guyca** [comment]
@ericlewis I must say I'm also a bit in the dark in regards to Fabric. I feel like there are a lot of unknowns here. I see that api's are still being added and changed quite frequently. We (Wix) don't have the capacity to take this integration on ourselves right now. @ericlewis if you want to lead this effort you're more than welcome but let's talk first on Discord to better coordinate this effort, either on RNN's channel or RN's.

**Comment by ericlewis** [comment]
Here is a bit of discussion on Fabric, plus links to better explanations. https://github.com/react-native-community/discussions-and-proposals/issues/4

I work / worked on making fabric work in OSS, as for enabling it in your own application, I recommend you check out RNTester in the react-native repo to see what you must do to enable it, also going to simplify this a bit, similar to auto linking. 

As for taking it on, I already have! This PR is *finished*. I’m running this PR in prod! I think I will modify it though, so that it can be turned on similar to how fabric is turned on in iOS land today. (Just make it a setting or subspec or operate on the RN_FABRIC_ENABLED flag. That way we can easier land it, and still works for everyone else.

**Comment by SudoPlz** [comment]
> react-native-community/discussions-and-proposals#4

Yep seen that.

> similar to how fabric is turned on in iOS land today

Interesting, I have NO ida how it's turned on in iOS land today. Aamof I don't know how it was turned on yesterday either.

That being said, I can't thank you enough for bringing that up, great work buddy, thank you so much.
Any idea what we have to do the same for Android? Do you not have an Android app in production yet?

**Comment by yogevbd** [comment]
@ericlewis Great work! I'm trying to enable fabric in our playground with no luck.. will be great if we can chat about it so I can test it and merge.
Please contact me on our discord chat or by mail: yogevbd@wix.com

**Comment by SudoPlz** [comment]
July 2020 and this is still open and unmerged.

I was working on enabling TurboModules on our project and bumped onto my comment from last year.

Wix (@yogevbd ) any plans on merging this one, and exposing delegates for https://github.com/wix/react-native-navigation/issues/5080 to support fabric?
If I open a PR for the second, will you take a look ?

**Comment by guyca** [comment]
@SudoPlz Would be amazing if you create another PR. Will you be available on Discord in case we have some questions?

**Comment by SudoPlz** [comment]
Sure thing @guyca , I'll be on discord all day today.

I've already worked on that locally to get our project to build, and here's the patch that we're using:

https://gist.github.com/SudoPlz/fffab570dcd9e50b18cf4c27ce6fd05c

This is breaking backwards compatibility with previous versions of react-native-navigation because it changes the `RCTBridgeDelegate` delegate from `ios/ReactNativeNavigation.m` to `AppDelegate.m` but I think that's inevitable because Fabric introduces more delegates that we need to become listeners for now: (`RCTCxxBridgeDelegate`, `RCTTurboModuleManagerDelegate` etc)

Let's discuss further about possible ways to handle this.
My patch is working for us now but maybe you want to deal with that some other way.

**Comment by guyca** [comment]
Alright, I wonder if we can introduce these changes in a backwards compatible manner. I'll let @yogevbd take it from here and will close this PR as it seems irrelevant now.

**Comment by SudoPlz** [comment]
@guyca Oh no, this PR is also needed.
Both of those changes are needed, this PR is needed to replace the Root View with RCTSurface, and my (future) PR is needed for using turbo modules and the new C++ bridge.

**Comment by SudoPlz** [comment]
Awesome, I'm super happy this got merged.

I started working on the TurboModules PR here:

https://github.com/wix/react-native-navigation/pull/6399

**Pull request merged**
