### PR TITLE
Support to React Native 0.52.0 (good PR)

### PR DESCRIPTION
**Pull request by Moreno97**
I come from  #2494.

Support to latest RN version on Android.

### CODE REVIEW

**Comment by DazChong** [comment]
Oops, Travis stuck..

**Comment by tiempham** [comment]
Is this ready for merge to master branch?

**Comment by anonrig** [comment]
@guyca

**Comment by ReggaePanda** [comment]
I get only a white screen with a `startSingleScreenApp` :/

`yarn add wix/react-native-navigation#2545/head`

**Comment by wwwdata** [comment]
@ReggaePanda had that problem as well but this PR is fixing it for me. Just download `android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadListenerReplacer.java` from this PR and replace that in your node_modules folder and recompile.

**Comment by ReggaePanda** [comment]
@wwwdata I did get this file with the yarn command

**Comment by ReggaePanda** [comment]
sorry, I did missing some file changes for installation

```
@Override
public String getJSMainModuleName() {
    return "index";
}
```

this PR works fine!

**Comment by Nodonisko** [comment]
Merge this please

**Comment by krystofcelba** [comment]
I have tested this PR and it doesn't work as expected. Well, the project gets compiled but actually, the ReactInstanceManagerDevHelper is not replaced because of `mDevInterface` field is no longer used in RN 0.52.0. Even if you fix the code of replacer no RedBox dialog will be shown for JS errors because of null returned from `getCurrentActivity` method of `DevCommandsHandlerProxy`. So I have created new PR with working implementation which is backwards compatible with RN ver. <= 0.51.0. Please check it here wix/react-native-navigation/pull/2580.

**Comment by brunolemos** [comment]
#2580 is preferred as it is backwards compatible.

**Pull request closed without merging**
