### PR TITLE
fixed a bug modal viewController was not deallocated when to call dis…

### PR DESCRIPTION
**Pull request by masarusanjp**
Fixed a bug that modal viewcontroller was not unregistered when to call dismissAllModals.

related PR: https://github.com/wix/react-native-navigation/pull/2255/files
Before merging #2255, the controller is always unregistered.
After merging #2255, the controller is often unregistered. So the dismissed controller was not deallocated.

### CODE REVIEW

**Comment by masarusanjp** [comment]
Please review @jasonmerino 
CC: @gran33

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by yershalom** [comment]
@yogevbd

**Comment by Crash--** [comment]
Thank you @masarusanjp this PR fix my issue!

**Pull request merged**
