### PR TITLE
Bump react-native version to 0.43

### PR DESCRIPTION
**Pull request by mdjnewman**
Builds on the fix in #903 but includes bumped react-native & react version for dev.

Related to facebook/react-native#12329

### CODE REVIEW

**Comment by ykzts** [comment]
@mdjnewman drop support for RN v0.42?

**Comment by mdjnewman** [comment]
Yes @ykzts, this change will require RN 0.43+.

Maybe this should go in v2 branch instead?

**Comment by mdjnewman** [comment]
I've just rebased from wix:master :)

**Comment by maxs15** [comment]
Awesome need this so bad ! Is it gonna be released in the next version ?

**Comment by inferusvv** [comment]
I am also really waiting for RN 0.43 support

**Comment by guyca** [comment]
@mdjnewman Thanks a lot for the pr. I merged #1040 which also addresses this issue but won't break users still using 0.42.

**Pull request closed without merging**
