### PR TITLE
Revert "Revert "Added support for the predictive back gesture on Android

### PR DESCRIPTION
**Pull request by yogevbd**
This reverts commit 2d247ce5b82d9de0de0f40c138eb2267b78f8972.

### CODE REVIEW

**Comment by vovkasm** [comment]
Sorry for late interruption, but why we corrupt files outside of project dir? I mean this change https://github.com/wix/react-native-navigation/pull/7653/files#diff-9319e9c2a463c6a4c862ec0a8695cb4dd9a859bbfd508bf81e8938685e92d2efR170

**Comment by lyswhut** [comment]
This PR caused v7.30.6 to fail to build on Windows platforms, where the following changes needed to be applied to work:

```diff
-def command = sdkDir.absolutePath + "/cmdline-tools/latest/bin/sdkmanager build-tools;" + buildToolsVersion
+def command = sdkDir.absolutePath + "/cmdline-tools/latest/bin/sdkmanager.bat build-tools;" + buildToolsVersion
```

**Comment by yogevbd** [comment]
> Sorry for late interruption, but why we corrupt files outside of project dir? I mean this change https://github.com/wix/react-native-navigation/pull/7653/files#diff-9319e9c2a463c6a4c862ec0a8695cb4dd9a859bbfd508bf81e8938685e92d2efR170

@evgeni-wix do we really need this?

**Comment by yogevbd** [comment]
> This PR caused v7.30.6 to fail to build on Windows platforms, where the following [changes](https://github.com/wix/react-native-navigation/issues/7619#issuecomment-1285637952) needed to be applied to work:
> 
> ```diff
> -def command = sdkDir.absolutePath + "/cmdline-tools/latest/bin/sdkmanager build-tools;" + buildToolsVersion
> +def command = sdkDir.absolutePath + "/cmdline-tools/latest/bin/sdkmanager.bat build-tools;" + buildToolsVersion
> ```

@lyswhut addressed [here](#7658 )

**Comment by lyswhut** [comment]
In v7.30.6, the system back key on the android platform seems to be invalid, and the back key cannot return to the desktop after clicking the return key. The last working version is v7.30.3

**Comment by evgeni-wix** [comment]
> > Sorry for late interruption, but why we corrupt files outside of project dir? I mean this change https://github.com/wix/react-native-navigation/pull/7653/files#diff-9319e9c2a463c6a4c862ec0a8695cb4dd9a859bbfd508bf81e8938685e92d2efR170
> 
> @evgeni-wix do we really need this?

@yogevbd It was really needed for build tools 33. Since the build tools version has been changed to 31, I suppose it can be removed. Need to check though.

**Comment by vovkasm** [comment]
I removed [this code](https://github.com/vovkasm/react-native-navigation/commit/e00464711f9853e362c8f899ec21e4b100130159) in our fork and nothing bad happened with build tools 33 (at least on linux and macos platforms). Moreover it fixed the build in our CI in which external connectivity very restricted (most external repos accessible only through cached proxy).

**Pull request merged**
