### PR TITLE
Send bottomTabSelected event

### PR DESCRIPTION
**Pull request by guyca**
The event is sent to the top most screen displayed in the current screenStack.

### CODE REVIEW

**Comment by messense** [comment]
Will iOS version support this?

**Comment by guyca** [comment]
Yes of course, hopefully this week.

**Comment by messense** [comment]
Seems that on Android this event will only be sent when switch between different tabs?
Meanwhile I find that on iOS the event is sent every time I tap on tab bar regardless of selecting same or different tabs.

**Comment by guyca** [comment]
The event should be sent only when the active bottom tab changed.  @messense Can you please open an issue?

**Pull request merged**
