### PR TITLE
V2 custom top bar

### PR DESCRIPTION
**Pull request by yogevbd**
```
  options: {
    topBar: {
      customTitleViewName: 'componentName'
    }
  }

  options: {
    topBar: {
      customViewName: 'componentName'
    }
  }
```

### CODE REVIEW

**Comment by SudoPlz** [comment]
Wow that looks good. It's basically what I've been waiting to hop on v2. Thanks @yogevbd

**Comment by SudoPlz** [comment]
@yogevbd would you be kind enough to also edit the README.md of v2 to indicate that a custom top bar is supported and how to use it? (If you have the time)

thank you

**Comment by yogevbd** [comment]
We are working on fixing the documentation. Hope it will be ready asap.

This is how you should use it:
```
Navigation.setRoot({
      stack: {
        children: [
          {
            component: {
              name: 'navigation.playground.TextScreen'
            }
          }
        ],
        options: {
          topBar: {
            customViewName: 'navigation.playground.CustomTopBar'
          }
        }
      }
    });
```

You can also set it as static options inside your component screen:
```
static get options() {
  return {
    topBar: {
      customViewName: 'navigation.playground.CustomTopBar'
    }
  };
}
```

`customViewName` expect any registered component by navigation (`Navigation.registerComponent()`)

**Comment by SudoPlz** [comment]
You're a rock star 🌟

**Comment by guyca** [comment]
@uggrock It's already implemented on Android, so the [documentation](https://wix.github.io/react-native-navigation/v2/#/docs/styling?id=options-object-format) for more info

**Pull request merged**
