### PR TITLE
Add font family support on bottom tabs

### PR DESCRIPTION
**Pull request by jp928**
in appStyle add attribute

``` javascript
tabFontFamily: 'Avenir-Medium.ttf' // for asset file
```
 or
``` javascript
tabFontFamily: 'sans-serif' // for existing fonts in system
```

### CODE REVIEW

**Comment by guyca** [comment]
Thanks for the pr @jp928 
Could you update the [docs](https://wix.github.io/react-native-navigation/#/styling-the-tab-bar) with this change?
Also, are you planning on making a pr for iOS as well?

**Comment by jp928** [comment]
@guyca 
I will update this on doc. But I do have plan to make this on IOS, should I update the document after I make this on IOS ?

**Comment by guyca** [comment]
Lets update the docs now, and mention that this property is currently only available on Android.

**Comment by jp928** [comment]
@guyca 
I can't access the link https://github.com/wix/react-native-navigation/docs, it gives me 404.
Please advise how to update the document.

**Comment by jp928** [comment]
In IOS this function was exposed in tabStyle, the syntax is something like:
```javascript
  Navigation.startTabBasedApp({
     ...tabs,
      tabsStyle: {
        tabBarTextFontFamily: 'Avenir-Medium'
      }
  })
```

**Comment by guyca** [comment]
This is the link: https://github.com/wix/react-native-navigation/tree/master/docs

**Comment by jp928** [comment]
@guyca 

Document has been updated.

**Pull request merged**
