### PR TITLE
Hack to fix when app is stuck on the splash screen.

### PR DESCRIPTION
**Pull request by BasitAli**
When the navigation activity is killed/restarted by the system, onCreate launches the SplashActivity and kills itself. The new SplashActivity starts context initialization but that is broken in between by the onDestroy of the NavigationActivity we just killed. This fix adds a boolean to disable destruction of js in this case.

### CODE REVIEW

**Comment by binbinla** [comment]
hello, same issue here, can this change fix the problem for you?

**Comment by BasitAli** [comment]
@binbinla It did. Using this branch on the app that I'm working on right now.

**Comment by irvingchenn** [comment]
@BasitAli LGTM

**Comment by badrange** [comment]
Hi @guyca I'd love to see your feedback on this PR. 

Upon committing #1838 you added a comment about a similar issue and how to prevent it, which you repeated the following day in https://github.com/wix/react-native-navigation/issues/1022#issuecomment-329432373

This doesn't work anymore - but @barhbie came up with a fix in https://github.com/wix/react-native-navigation/issues/3243#issuecomment-406208403

I have tested both methods, and they both work for our use case. @BasitAli 's solution is the simplest one, is there anything that prevents this from being merged?

**Comment by skovhus** [comment]
This works for us. We avoid killing the navigation state every time the app opens from the background and we can now assume the app although the activity is killed. 👍

**Comment by tigo0** [comment]
Would be awesome to have this merged soon. Thanks.

**Comment by kevinkevw** [comment]
Can anyone review this one and perform a merge? 

The current Navigation.isAppLaunched() way is not very ideal and many users reported it blocks the navigator to proceed, all navigator functions not able to run. ( not sure the reasons yet but got reports from various Android OS )

**Comment by asolas** [comment]
same as home button, a new screen created each time.
test

**Pull request merged**
