### PR TITLE
Refactor options

### PR DESCRIPTION
**Pull request by yogevbd**

### CODE REVIEW

**Comment by henrikra** [comment]
@yogevbd @guyca Btw do you guys have some internal documentation for description of these PRs? Because many times there are pull requests named something like "Refactor options" without any description so it is hard to see for example what problem this PR is solving.

Good to see PRs are coming though :D

**Comment by yogevbd** [comment]
Your'e right! next time I'll add specific description for the PR's..
This PR solves #3697 
The main thing here is to have consistent interface for all layout types in order to enable better support in complex layouts

**Comment by henrikra** [comment]
Sounds very good!

**Comment by rgoldiez** [comment]
I had to roll this PR back in our app as it seems to not merge in the options.  Works fine on the immediately prior release.

**Comment by yogevbd** [comment]
@rgoldiez Can you explain when exactly merging options fails? thanks

**Comment by rgoldiez** [comment]
@yogevbd - Sure, I should have been more clear with my prior comment.

When performing `setRoot` as I am below, the `sideMenu` options are not applied (none of them).  Works fine in `2.0.2545`
```
Navigation.setRoot({
  root: {
    sideMenu: {
      left: {
        component: {
          name: 'leftDrawer',
          id: 'leftDrawer',
        },
      },
      center: {
        stack: {
          id: 'stackRoot',
          children: [{
            component: {
              name: 'entry',
            },
          }],
          options: {
            topBar: {
              title: {
                // text: 'Pushed screen title'
              }
            },
            sideMenu: {
              left: {
                width: hbConstants.drawerWidth * Dimensions.get('window').width,
                shouldStretchDrawer: false,
                animationVelocity: 3750,
                animationType: 'parallax',
              },
            }
          }
        }
      }
    }
  }
});
```

When showing a modal, I fire it from a common redux saga as show below.  `defaultModal` is further below.  Those aren't being applied either.
```
    Navigation.showModal({
      stack: {
        children: [{
          component: {
            name: modalType,
            passProps,
            options: {
              topBar: {
                title: {
                  text: title,
                },
                subtitle: {
                  text: subtitle,
                  fontSize: 10,
                }
              }
            }
          },
        }],
        ...hbConstants.defaultModal,
      }
    });
```

```
export const defaultModal = {
  options: {
    topBar: {
      rightButtonColor: '#202020',
      leftButtonColor: '#202020',
      title: {
        color: '#202020',
        fontFamily: 'SalesforceSans-Bold',
      },
      subtitle: {
        color: '#202020',
        fontFamily: 'SalesforceSans-Regular',
        subtitle: 10,
      },
      backButton: {
        title: '',
        showTitle: false,
      },
      background: {
        color: '#F0F0F0',
      },
    },
  }
}
```

**Comment by yogevbd** [comment]
@rgoldiez Fixed here: 69c3e0dea8f36011e1ca75a131f006462d1e38ab

**Pull request merged**
