### PR TITLE
[Android] Ajust FAB icon size

### PR DESCRIPTION
**Pull request by Fuhrmann**
As of today, the floating action button, when provided an icon always set the size bigger then the specified  in the material design guideline:

**Wrong**
image

Even if we provide a icon 24x24 the fab icon will always have the same size (auto resize is happening). This changes set the scale type of the fab to CENTER. This way, when you provide the icon with the correct size (24) you should get this:

**Correct**
image

------

image

------

image

**An important thing to note**

Introducing this scale type will prevent the FAB to auto resize the icon. Let's say the user provide an icon 50x50. This should be the result (`which I think it's not a problem`):

image

I tested this in API 19, 22 and 25.

This fix the problem pointed out in the #1309.

### CODE REVIEW

**Comment by jakewtaylor** [comment]
Thanks, this works great.

Any reason for not merging @guyca?

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by mths0x5f** [comment]
If I remember correctly, v1 PRs will be not processed anymore.

**Comment by jakewtaylor** [comment]
This really doesn't need to be marked as stale. It's a simple PR with no conflicts that I can see.

Is v1 completely unsupported now?

**Pull request closed without merging**
