### PR TITLE
[WIP, Android] Fixing TopTabs

### PR DESCRIPTION
**Pull request by Damar95**
Currently working on fixing the topTabs.
I will commit new fixes over time, if im able to fix somethink...
I would also  appreciate help :)

The first Commit fixes problems with merging navigation style.

### CODE REVIEW

**Comment by Damar95** [comment]
Issues:
#5375 
#5376

Bugs:
- [ ] toptab Margin
- [ ] top Navigation goes under the android statusbar if tab gets changed

**Comment by guyca** [comment]
@Damar95 This is great! Ping me on Discord if I can help with anything 🙇

**Comment by mayconmesquita** [comment]
Hi @Damar95, i haven't had time yet. Btw, awesome commit!

**Comment by charpeni** [comment]
Do we know why #5375 is happening? Do we have any solution for this?

This is blocking us from upgrading to RN 0.60 and RNN v3. Happy to help if I can have a quick status sync.

**Comment by syedabuthahirm** [comment]
@Damar95 [here](https://github.com/wix/react-native-navigation/issues/5228#issuecomment-505239007) i mentioned some style issues (tob tab selected border color and border width) can you look at them.

**Comment by oxyii** [comment]
@Damar95 one more check item please: TopTabs placed inside some stack. If pushing new screen into parent stack then topTabs already hide but topBar height still include topTabs height.

P.S. Sorry for my english

**Comment by ldipasquale** [comment]
@guyca can you merge it? I know you are not supporting right now TopTabs but it solves a lot of issues and make it usable.

**Pull request closed without merging**
