### PR TITLE
Fix immutable error after updating rn@0.35

### PR DESCRIPTION
**Pull request by WhatAKitty**
using deep clone. #394

### CODE REVIEW

**Comment by indivisable** [comment]
This fixed some issues I had with 0.31 as well (having to do with opening Models) - Reference: https://github.com/wix/react-native-navigation/issues/394

**Comment by rawrmaan** [comment]
Just a heads up for MobX users, this will cause you to lose referential integrity and observability when passing props to a new view or modal via `passProps`.

**Comment by DanielZlotin** [comment]
I'm accepting this as a temporary fix, will be removed before 2.0.0

**Comment by stonecold123** [comment]
@rawrmaan 
I'm using the @next version. 
I tried passing the mobx store via `passProps` to another screen and update a new value in the store, 
I'm getting 
````
You attempted to set the key K with the value X on an object that is meant to be immutable and has been frozen
````
What's your workaround for this problem?

**Comment by stonecold123** [comment]
The issue with passing mobx via passProps not being observable still remains. Is there any solutions?

**Pull request merged**
