### PR TITLE
Ignore pan gesture when no drawer is enabled

### LINKED ISSUE #2352: Drawer swipe gesture steals all events from PanResponder > 10px delta
### Issue Description

`onPanResponderMove` only called for 10px or so (the slop threshold, I assume), then the drawer gesture takes over. No other `PanResponder` lifecycle events are called after it takes over.

screen shot 2017-12-14 at 6 12 08 pm

Disabling the drawer gesture with `disableOpenGesture` fixes this. But we'd like to keep the drawer gesture.

### Steps to Reproduce / Code Snippets / Screenshots

Create a single page app with a drawer and the swipe gesture enabled. Create a component with this pan responder in the root component:

```js
this._panResponder = PanResponder.create({
  onStartShouldSetPanResponder: () => true,
  onStartShouldSetPanResponderCapture: () => true,

  onMoveShouldSetPanResponder: () => true,
  onMoveShouldSetPanResponderCapture: () => true,

  onPanResponderMove: (e, gestureState) => {
    console.log('onPanResponderMove', gestureState.dx, gestureState.dy)
  },
  onPanResponderGrant: (evt, gestureState) => {
    console.info('onPanResponderGrant')
  },
  onPanResponderReject: evt => {
    console.info('onPanResponderReject')
  },
  onPanResponderTerminationRequest: () => {
    console.log('onPanResponderTerminationRequest')
    return false
  },
  onShouldBlockNativeResponder: () => true,
})
```

Try to swipe down on your component.

---
### Environment
* React Native Navigation version: 1.1.309
* React Native version: 0.50.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iphone 6 simulator debug

### PR DESCRIPTION
**Pull request by akmjenkins**
Fixes #2352 

PanResponder callbacks do not work correctly if a RNN drawer was inited, but later disabled. 

In the instance of a left drawer, for example, this pull request will allow the following code to prevent RNN from "stealing" a gesture:

```
onPanResponderGrant: (e, gestureState) => {
    props.navigator.setDrawerEnabled({side:'left',enabled:false});
    ...
},
onPanResponderRelease: (e, gestureState) => {
    props.navigator.setDrawerEnabled({side:'left',enabled:true});
    ...
}

```

### CODE REVIEW

**Comment by ignacioola** [comment]
@akmjenkins Thanks for the PR, this solved the issue for me.

**Comment by azabost** [comment]
@akmjenkins Helped me a lot! Thanks 👍

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by StasDoskalenko** [comment]
This works for me fine.

**Comment by FlaviooLima** [comment]
@DanielZlotin  @guyca 
Can someone approve this PR?

**Comment by FlaviooLima** [comment]
Pls merge :)

**Pull request closed without merging**
