### PR TITLE
Add tabBarDisableIconTint option for TabBar icons on iOS (#1710)

### PR DESCRIPTION
**Pull request by gvillenave**
This PR adds new `tabBarDisableIconTint` and `tabBarDisableSelectedIconTint` options to AppStyle for iOS to avoid overriding the tab bar icon colors with `tabBarButtonColor`, as discussed in #1710.

### CODE REVIEW

**Comment by viventus** [comment]
so?

**Comment by sercanov** [comment]
Couldn't manage to properly show an image with color & opacity. This PR solved it, my tabbar icons came back to life, they are so colorful right now. Isn't it going to merge ?

**Comment by yershalom** [comment]
Can one of the admins verify this patch?

**Comment by ossamaweb** [comment]
👍

**Pull request closed without merging**
