### PR TITLE
Allow loading of System images on Android

### LINKED ISSUE #6594: Document sf symbols usage
### Issue Description

Recently we introduced usage of sf symbols for all `icon` props for ios. This needs to be documented. See https://github.com/wix/react-native-navigation/pull/6576

### PR DESCRIPTION
**Pull request by mateioprea**
This is an addition for PR #6576 and will fix #6594.

### CODE REVIEW

**Comment by mateioprea** [comment]
I still need to document things, that's why this is still draft.

**Review by guyca — CHANGES_REQUESTED** [review]

**Comment by guyca** [comment]
Hey @mateioprea ! PR looks good! 🔥 🔥 🔥 
I left a few code change suggestions. Also, we should add a link to the list of available icons available in the documentation. I'm still no clear on the which icons are available 🤔

**Comment by mateioprea** [comment]
@guyca this is ready for review now. Managed to get the docs in place. Can you take a look? Thank you!

**Comment by mateioprea** [comment]
Maybe @danilobuerger can take a look here as well.

**Comment by guyca** [comment]
@mateioprea Following the discussion on Discord, should we close the PR for now?

**Comment by mateioprea** [comment]
@guyca yes. I’ll close it now.

**Comment by danilobuerger** [comment]
@mateioprea @guyca Since I was tagged here, why was it closed?

**Comment by guyca** [comment]
@danilobuerger, @mateioprea and I were discussing this PR on Discord and came to the conclusion that Android doesn't have an equivalent to SF Symbols. The icons available in `android.R.drawable` are not meant to be used by applications and are extremely limited in variety.

The closes to SF Symbols is Android's [Material design icons](https://material.io/resources/icons/?style=baseline) but those need to be bundled individually in the app.

**Comment by danilobuerger** [comment]
I see. We should keep the documentation update from this PR though.

**Pull request closed without merging**
