### PR TITLE
Fixed dismissAllModals for iOS

### PR DESCRIPTION
**Pull request by sotownsend**
Fixed dismissAllModals for iOS - Previously it would unregister things like the tab bar that it shouldn't have. #284 #1598 #418

### CODE REVIEW

**Comment by shuse2** [comment]
when will this be published on npm?

**Comment by CherishIt** [comment]
could this PR be merged?

**Comment by jasonmerino** [comment]
I too would love to see this merged. It would be more useful for handling deep links that come into the app and we don't want to keep track of how many modal layers deep we are on the off chance that there are two displayed.

**Comment by sotownsend** [comment]
We've been using this in production for a few weeks without any mishaps.

**Comment by gran33** [comment]
Solved in 
https://github.com/wix/react-native-navigation/pull/2255

**Pull request closed without merging**
