### PR TITLE
[v2] Add styling to tab bar

### PR DESCRIPTION
**Pull request by neilkimmett**
I copied the style for `tabsStyle` from the docs for v1 https://wix.github.io/react-native-navigation/#/styling-the-tab-bar

We depend on this for our app so I'm keen to get it into upstream. Let me know if this isn't where/how y'all were thinking of doing tab styling and I can move it elsewhere.

### CODE REVIEW

**Comment by DanielZlotin** [comment]
@neilkimmett thanks for the PR,
this needs to be moved to be a child of navigationOptions (same place you have the topBar styles)
so if you can, put it in one of the screens of the tabs.
```
static navigationOptions: {
    tabs: { ... }
}
```

same goes to the `title` property.

Another feature that's missing is passing navigationOptions as part of the commands (for example push, setRoot etc.) so if you want you can add support to that as well

**Comment by neilkimmett** [comment]
OK cool I'll have a crack at that tomorrow. Just to clarify it'd be like:
```
static navigationOptions: {
    tabs: {
        'tabBarTextColor': processColor('#AAA'),
        'tabBarSelectedTextColor': processColor('#FFF'),
        'tabBarTextFontFamily': 'Helvetica',
        'tabBarTextFontSize': 14,
    }
}
```

Not quite sure I understand re: `title`; seems like the more natural place for that is when creating the tabs in `setRoot` ?

**Comment by neilkimmett** [comment]
@DanielZlotin I've moved the tab styling stuff to navigationOptions, let me know what you think.

**Comment by neilkimmett** [comment]
Also I can rebase and squash this all into a single commit on top of the latest `v2` branch if you'd like to get rid of those merge commits.

**Comment by neilkimmett** [comment]
Did the title thing in https://github.com/wix/react-native-navigation/pull/2072

**Comment by yogevbd** [comment]
@neilkimmett there were too many conflicts so I had to fetch your changes in new branch.
#2571

**Pull request closed without merging**
