### PR TITLE
Fix Android TopTabs

### PR DESCRIPTION
**Pull request by supermaverickws**
Happy To My First Request

### CODE REVIEW

**Comment by guyca** [comment]
Hey @supermaverickws 👋 
Thanks a lot for taking the time to address TopTabs!! Would appreciate it if you could reach out to me on Discord so we can better coordinate this task.

Unfortunately I'm a bit preoccupied this week so I might not have time to review the PR. In the mean time, I noticed 4 unit tests failed in CI. You can check that out by running tests locally either in CMD via `npm run test-unit-android` or from Android Studio.

**Comment by supermaverickws** [comment]
@guyca I fix 4 tests errors and other topTabs changes. You can check that.

**Comment by guyca** [comment]
Hey @supermaverickws! Thanks a lot for the PR!! 🙇 
Thank you so much for taking the time to work on it. I've merged it into a branch, and not into master. There are a few issues I'd like to discuss, lets continue the conversation on Discord and figure out how we can move forward with this effort?

**Comment by supermaverickws** [comment]
@guyca OK.Agree discuss.  start it.

**Comment by zachgibson** [comment]
@supermaverickws @guyca any updates on this discussion?

**Comment by guyca** [comment]
Hey @zachgibson 👋 
TopTabs layout is not in our plans at the moment due to our limited capacity. We'd love to collaborate with a company how's willing to take on the development of this layout for both platforms. As always, We can be reached on Discrod.

**Comment by zachgibson** [comment]
Sounds good. Thank you for the update @guyca :)

**Pull request merged**
