### PR TITLE
fixing typo causing subtitle text color cant be changed... + fixing props on showInAppNotification..

### PR DESCRIPTION
**Pull request by MeKarina**
i cant change subtitle text color...

see here https://github.com/wix/react-native-navigation/blob/master/ios/Helpers/RCCTitleViewHelper.m#L152

it should be `navBarSubtitleTextColor`,, not `navBarTextSubtitleColor`...

### CODE REVIEW

**Comment by MeKarina** [comment]
i incidentally adding unrelated commit to this pull request n i dont know how to revert commit…. X_X

2nd commit:
props on showInAppNotification not working properly…

after digging some code i notice that each api has `savePassProps(params)`,, not this one so i guess u forgot to add them.. 

this 2nd commit simply add `savePassProps(params)` to `showInAppNotification(params)` function…

after this change props on `showInAppNotification` is working properly...

**Comment by vyky** [comment]
@DanielZlotin @guyca 

This fixes https://github.com/wix/react-native-navigation/issues/635

**Comment by guyca** [comment]
Thanks for the PR @MeKarina 
`navBarTextSubtitleColor` is the name of the property on Android as well, so lets keep it as is for now. If it doesn't work on iOS, it might mean that the native side is expecting the wrong property name.

Can you create a separate PR for the inAppNotification issue?

**Comment by vyky** [comment]
@MeKarina will you by any chance create PR for showInAppNotification? I need this PR. If not, I’ll do it for you.

**Comment by MeKarina** [comment]
Uhh,, sorryy im away from my laptop until the end of this month,, please do it n thank Youu...

**Pull request closed without merging**
