### PR TITLE
Fix link script on iOS

### PR DESCRIPTION
**Pull request by yogevbd**
Sets the minimum iOS version to iOS 11.0 which is the minimum version required by the library.

### CODE REVIEW

**Review by danilobuerger — APPROVED** [review]
Looks good, although as previously discussed could have side effects if the podfile was previously modified. This could alter the platform of other targets or downgrade the version if previously set higher.

**Comment by yogevbd** [comment]
@danilobuerger nice catch! fixed.

**Review by danilobuerger — APPROVED** [review]

**Comment by danilobuerger** [comment]
Looks good, didn't test though.

**Comment by yogevbd** [comment]
@danilobuerger tested it in multiple cases so I think we're good to go.

**Pull request merged**
