### PR TITLE
[V3, Android] Fix Fab Gravity and Margin

### PR DESCRIPTION
**Pull request by Damar95**
Fix Fab Gravity for V3
ifx for #5305

### CODE REVIEW

**Comment by Damar95** [comment]
The margin is still wrong. it seems like it uses the Display and not the inner View.
Because of this the Fab might be hidden behind the TopBar/Tabs or BottomTabs

**Comment by Damar95** [comment]
I added a commit which "fixes" the margin at the bottom.
The problem is, that ist still not correct because the height returned by [getBottomInset()](lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L387) is to much as the screenshot showes


and with the spacing margin and bottomTabs margin its lookes like this
grafik
grafik

**Comment by Agungkes** [comment]
```
Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [
            {
              stack: {
                children: [
                  {
                    component: {
                      name: 'example-stack',
                    },
                  },
                ],
                options: {
                  bottomTab: {
                    text: 'First',
                    icon: bookOpen,
                  },
                  fab: {
                    id: 'test-fab',
                    visible: true,
                    actions: [
                      {
                        id: 'act-1',
                      },
                      {
                        id: 'act-2',
                      }
                    ]
                  }
                },
              },
            },
            {
              component: {
                name: 'example-1',
                options: {
                  bottomTab: {
                    text: 'example',
                    icon: award,
                  },
                },
              },
            },
            {
              component: {
                name: 'example-test',
                options: {
                  bottomTab: {
                    text: 'example2',
                    icon: user,
                  },
                },
              },
            },
          ]
        },
      },
    });
```
That's my Navigation hierarchy. 

All went well until I switched screens using bottomTabs. After I move to the next then return again, then this error message appears
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams com.reactnativenavigation.views.Fab.getLayoutParams()' on a null object reference
```
I just want to use fab on the first bottomTabs

**Comment by Damar95** [comment]
@Agungkes i added a new commit which should fix this crash.
Thanks for the detailed error description. :)

**Comment by Damar95** [comment]
@Agungkes as you described in #5447 some options dont work. i added a fix for the visable attribut in the last commit, even its not part of this PR.

Might look into it, but i'm not effected by this bugs so i don't know when...

@guyca You can merge this PR.

**Comment by Agungkes** [comment]
@Damar95 only icon option don't work, so can't change "plus".
 
Hope this PR will merge soon :D thanks @Damar95

**Comment by Damar95** [comment]
@guyca the tests are failing because of this line: https://github.com/Damar95/react-native-navigation/blob/57b5c43980a6be6779b609a0ec0c9880f14f436f/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L406

`fabOptionsPresenter.applyTopInset(getTopInset(getCurrentChild()));`

Calling `fabOptionsPresenter.applyTopInset()` with any int as param works.
Calling `getCurrentChild()` works.
Calling `getTopInset(getCurrentChild())` does not work.

Do you know why?

**Comment by omid-ebrahimi** [comment]
We really need this fix. Please merge it.

**Comment by Damar95** [comment]
@omid-ebrahimi, @guyca is not avaiable this week and can't fix the unit tests.

We also found a other problem we need to fix, which needs to be fixed.

**Comment by itsam** [comment]
Could you please advise how to apply this PR to my instance until it is merged in master?
Also, any timeplan when (and if) will be merged to master wiil be highly appreciated.

Thanks

**Comment by lb90** [comment]
+1

**Comment by itsam** [comment]
@Damar95 any news on this?  Thank you in advance!

**Pull request closed without merging**
