### PR TITLE
[V2] Fix iOS pop gesture when topBar is hidden

### LINKED ISSUE #4455: [V2] iOS back gesture doesn't work when topBar or backButton is hidden
### Issue Description

Back gesture doesn't work when topBar or backButton's visible set to false

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.push(this.props.componentId, {
  component: {
    name: 'example.PushedScreen',
    passProps: {
      text: 'Pushed screen'
    },
    options: {
      topBar: {
        visible: false
      }
    }
  }
});
```
or
```javascript
Navigation.push(this.props.componentId, {
  component: {
    name: 'example.PushedScreen',
    passProps: {
      text: 'Pushed screen'
    },
    options: {
      topBar: {
        backButton: {
          visible: false
        }
      }
    }
  }
});
```

---
### Environment
* React Native Navigation version: 2.2.1-snapshot.61 
* React Native version: 0.57.7
* Platform(s): iOS
* Device info: Both simulator & device, iOS 12, Both debug & release

### PR DESCRIPTION
**Pull request by rawrmaan**
Fixes #4455.

The broken-ness of this feature stems from an iOS bug. I adapted the fix from this StackOverflow answer: https://stackoverflow.com/questions/24710258/no-swipe-back-when-hiding-navigation-bar-in-uinavigationcontroller/41895151#41895151 It seemed like the most well-thought-out and bulletproof fix out of all the answers.

I did thoroughly test this to make sure `popGesture` works with the nav bar hidden and visible, but I did not add any e2e tests. I would like some guidance on how to test something like this (a swipe gesture) if anyone could help, as I'm not very familiar with the `XCTest` framework.

Thanks for an amazing library! There really is nothing close out there!

### CODE REVIEW

**Comment by MasoudAlali** [comment]
I tested these changes and it works
I'm waiting for next release and I hope this problem will be fixed
thanks

**Comment by LRNZ09** [comment]
This would be really useful

**Comment by tunegov** [comment]
Merge this, please!!!

**Comment by gorjuspixels** [comment]
@guyca hey, other than the conflicts, what are the requirements to have this merged? do we need tests for this? i dont see any rn

**Comment by kyle-ssg** [comment]
This probably fixes two of my open issues, any reason why this is not merged?

**Comment by Rigellute** [comment]
@rawrmaan thank you so much for doing this.

Do you have an idea for when this PR could be merged?

**Comment by mackiedrew** [comment]
@guyca What can we do to help the merge along?

**Comment by Rigellute** [comment]
Another way of fixing this would be to revert this change https://github.com/wix/react-native-navigation/commit/11a174b31ab549a5d075ff1d0026f864fa237419

The bug that this change was fixing `Fix popGesture freezes the app` can be worked around by doing this in your root component
```js
componentDidAppear() {
    Navigation.mergeOptions(this.props.componentId, {
        popGesture: false,
    });
}

componentDidDisappear() {
    Navigation.mergeOptions(this.props.componentId, {
        popGesture: true,
    });
}

```

**Comment by moonou** [comment]
I like this PR, I upgrade version to `2.14.0-snapshot.246` for the pop gesture, but when I use gesture to pop page, I found `registerCommandListener` wasn't called. Does anybody have some idea for this?

**Comment by guyca** [comment]
@moonou the command listener is invoked only when `Navigation.pop` command is invoked.

**Comment by dangkhoa2708** [comment]
` Navigation.push(this.currentScreen, {
      component: {
        id: screenID,
        name: screenID,
        passProps: params,
        options: {
          popGesture: true,
          bottomTabs: {
            visible: false,
            drawBehind: true
          },
          statusBar: {
            backgroundColor: 'white'
          },
          animations: {
            push: {
              content: {
                x: {
                  from: 1000,
                  to: 0,
                  duration: 250
                }
              }
            },
            pop: {
              content: {
                x: {
                  from: 0,
                  to: 1000,
                  duration: 250
                }
              }
            }
          }
        }
      }
    })`

First of all, thank you for this awesome library, I ran into the pop gesture issue when the top bar is hidden. I've been following this issue from when it was not merged until now. But I still can not make it work. Am I doing it wrong ? Very appreciated with any help.

I'm using version 2.16

**Pull request merged**
