### PR TITLE
Add support to pass any argument to <Provider />

### PR DESCRIPTION
**Pull request by edvinasbartkus**
I would like to suggest this change for `registerComponentWithRedux` method. For the last argument to accept a set of props that can be passed to `<Provider />`. This is backward compatible, but additionally, it would enable new use cases:

1. Using [unstated](https://github.com/jamiebuilds/unstated) instead of `redux`:

```js
import { Provider, Subscribe, Container } from 'unstated'

class Counter extends Container {
// ...
// <as per https://github.com/jamiebuilds/unstated#example>
// ...
}

Navigation.registerComponentWithRedux('screen.Home', () => HomeScreen, Provider, {inject: [counter]})
```

2. Enable `persistor` for redux

```js
import 'redux-persist'

const persistor = ...

Navigation.registerComponentWithRedux('screen.Home', () => HomeScreen, Provider, {store: store, persistor: persistor})
```

### CODE REVIEW

**Comment by henrikra** [comment]
I think we should totally remove Redux dependency from this project and make view rendering in a way that any libraries can be used. We talked about this @guyca

**Comment by guyca** [comment]
I'm all for removing any reference of redux from RNN. I think for now we can improve upon the solution proposed by @edvinasbartkus and deprecate `wrapWithRedux` in favor of a more general implementation; `wrapWithProvider`.

```js
static wrapWithProvider(WrappedComponent: React.ComponentClass<any>, Provider: any, providerParams: any): React.ComponentClass<any> {
    class ReduxWrapper extends React.Component<any, any> {
      render() {
        return (
          <Provider {...providerParams}>
            <WrappedComponent {...this.props} />
          </Provider>
        );
      }
    }
```

while still limited, it's less coupled on redux and doesn't include workarounds like the ternary operator checking `dispatch`. What do you guys think?

**Comment by henrikra** [comment]
Yeah this is bit better. Maybe `wrapWithComponent` is more generic? Can you @edvinasbartkus try to make the more generic solution for this until we can totally remove redux and all wrap hacks from RNN?

**Comment by edvinasbartkus** [comment]
@henrikra @guyca sounds great about having a generic solution for any type of the wrapper. WIll make the changes for the PR later today.
Thanks!

**Comment by edvinasbartkus** [comment]
@henrikra @guyca 
Updated the PR with the new `registerComponentWithProvider` method.
Should I add backward capability to call `registerComponentWithRedux`?

**Comment by henrikra** [comment]
Before going through the PR can you show me examples of how to use this `registerComponentWithProvider`?

**Comment by edvinasbartkus** [comment]
1. In my case where I am using it with `unstated`

```js
import {Provider, Container} from 'unstated'
const container = new CustomContainer(data: []) // extends Container

Navigation.registerComponentWithProvider('screen.HomeScreen', () => HomeScreen, Provider, {inject: [container]})
```

```js
const HomeScreen = () => <Subscribe to={[CustomContainer]}>{container => <View />}</Subscribe>
```


2. In case of good old redux
```
import {Provider} from 'react-redux'

const store = 

Navigation.registerComponentWithProvider('screen.HomeScreen', () => HomeScreen, Provider, {store})
```

**Comment by henrikra** [comment]
Hmm okay. I think this solution is better 👍 

Would it possible to do even more generic solution? That we would need only one `registerComponent` which can handle all the cases. The usage would be something like this
```ts
// with redux

import { Provider } from 'react-redux';
import { createStore } from 'redux';

import Home from './myScreens/Home';

const store = createStore();

Navigation.registerComponent('screen.HomeScreen', Home, WrappedComponent => (
  <Provider store={store}>
    <WrappedComponent />
  </Provider>
));

// with unstated
import { Provider, Container } from 'unstated';
const container = new CustomContainer({ data: [] });

Navigation.registerComponent('screen.HomeScreen', Home, WrappedComponent => (
  <Provider inject={[container]}>
    <WrappedComponent />
  </Provider>
));

// with nothing special
Navigation.registerComponent('screen.HomeScreen', Home, WrappedComponent => <WrappedComponent />);

```

What do you think @edvinasbartkus @guyca ?

**Comment by henrikra** [comment]
Can you make wip pr so it is easier to look at?

**Comment by guyca** [comment]
Figured out what the issue was :(
I registered my test screen twice by mistake, the second time without wrapping it with providers 🤦‍♂️

**Comment by guyca** [comment]
Alright, published my [PR](https://github.com/wix/react-native-navigation/pull/4427) - @edvinasbartkus @henrikra your reviews and opinions is appreciated.

**Comment by guyca** [comment]
After looking into this more, I realised there's no need for another api to wrap components with providers, we can use the existing `registerComponent` api by passing a functional component to it as shown in #4427

**Pull request closed without merging**
