### PR TITLE
Use View from React Native

### PR DESCRIPTION
**Pull request by svbutko**
Should be hot fixed since it leads to a crash
image

### CODE REVIEW

**Review by kr4ckhe4d — DISMISSED** [review]

**Comment by kr4ckhe4d** [comment]
Could be related to this issue

Screen Shot 2021-10-05 at 3 06 27 pm

**Comment by svbutko** [comment]
> Could be related to this issue
> 
> Screen Shot 2021-10-05 at 3 06 27 pm

Yes, it is

**Comment by svbutko** [comment]
CI probably has UI lib installed and therefore not failing

**Comment by swabbass** [comment]
I think we can remove the import from ui-lib of `View` and use the one from react-native.....

**Comment by svbutko** [comment]
> I think we can remove the import from ui-lib of `View` and use the one from react-native.....then no need to move dependencies.

Dropped the commit and changed imports

**Review by swabbass — APPROVED** [review]
Great!

**Comment by MadaShindeInai** [comment]
Screenshot 2021-10-05 at 12 14 51

**Comment by svbutko** [comment]
@MadaShindeInai the build is still building, it's going to be fixed in next version `7.23.0` or some other, higher than `7.22.0`

**Comment by MadaShindeInai** [comment]
@svbutko thx. I'm new and saw another issue with title 7.21->7.22 and thought it fixed in 7.22 =)
okey, so will wait =)

**Comment by yogevbd** [comment]
@svbutko @MadaShindeInai  @swabbass fix is available in 7.22.1 🥳

**Pull request merged**
